-- Migration 014: ASVAB Word Knowledge Questions
-- 150 Word Knowledge questions for ASVAB AFQT prep
-- test_types = ARRAY['ASVAB'] — these are ASVAB-specific vocabulary questions
-- Difficulty 1 = straightforward synonym, 2 = moderate, 3 = harder/contextual
-- Format: multiple choice, 4 options, standard ASVAB WK style
-- — Benjamin Rodriguez

DO $$
DECLARE
  q_ids UUID[];
BEGIN

-- ─────────────────────────────────────────────────
-- BATCH 1: Direct synonym format (difficulty 1-2)
-- ─────────────────────────────────────────────────

INSERT INTO questions (section, difficulty, question, options, correct_answer, explanation, test_types)
VALUES

('Word Knowledge', 1,
 'ABUNDANT most nearly means:',
 '["Scarce","Plentiful","Expensive","Hidden"]',
 'Plentiful',
 'Abundant means existing in large quantities. Plentiful is the closest synonym. Scarce is the antonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'ACCELERATE most nearly means:',
 '["Slow down","Turn around","Speed up","Stop"]',
 'Speed up',
 'To accelerate means to increase speed or rate. "Speed up" is the direct synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'ACCURATE most nearly means:',
 '["Careful","Correct","Quick","Thorough"]',
 'Correct',
 'Accurate means free from error or conforming exactly to truth. Correct is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'ADEQUATE most nearly means:',
 '["Excellent","Insufficient","Satisfactory","Excessive"]',
 'Satisfactory',
 'Adequate means enough to satisfy a requirement. Satisfactory is the closest match.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'ADJACENT most nearly means:',
 '["Distant","Nearby","Similar","Opposite"]',
 'Nearby',
 'Adjacent means next to or adjoining. Nearby captures this spatial relationship.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'ADVERSARY most nearly means:',
 '["Ally","Partner","Opponent","Supervisor"]',
 'Opponent',
 'An adversary is someone who opposes or fights against another. Opponent is the direct synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'AGILE most nearly means:',
 '["Clumsy","Nimble","Strong","Slow"]',
 'Nimble',
 'Agile means able to move quickly and easily. Nimble is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'ALLOCATE most nearly means:',
 '["Collect","Distribute","Borrow","Destroy"]',
 'Distribute',
 'To allocate means to distribute resources for a specific purpose. Distribute is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'AMBIGUOUS most nearly means:',
 '["Clear","Uncertain","Incorrect","Obvious"]',
 'Uncertain',
 'Ambiguous means open to more than one interpretation. Uncertain best captures this meaning.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'AMPLIFY most nearly means:',
 '["Reduce","Increase","Measure","Distort"]',
 'Increase',
 'To amplify means to make larger or louder. Increase is the direct synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'APPREHEND most nearly means:',
 '["Release","Capture","Understand","Ignore"]',
 'Capture',
 'Apprehend means to seize or arrest. In the context of law enforcement, capture is the closest match.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'ARDUOUS most nearly means:',
 '["Simple","Difficult","Dangerous","Boring"]',
 'Difficult',
 'Arduous means requiring much effort; hard. Difficult is the direct synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'ASTUTE most nearly means:',
 '["Foolish","Stubborn","Clever","Generous"]',
 'Clever',
 'Astute means having sharp judgment or insight. Clever is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'AUDACIOUS most nearly means:',
 '["Timid","Bold","Careless","Quiet"]',
 'Bold',
 'Audacious means showing a willingness to take surprising or daring risks. Bold is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'AUTHORIZE most nearly means:',
 '["Deny","Permit","Request","Require"]',
 'Permit',
 'To authorize means to give official permission. Permit is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'BENEFIT most nearly means:',
 '["Drawback","Advantage","Requirement","Expense"]',
 'Advantage',
 'A benefit is something that is advantageous or helps. Advantage is the direct synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'BELLIGERENT most nearly means:',
 '["Peaceful","Hostile","Brave","Careless"]',
 'Hostile',
 'Belligerent means hostile and aggressive. Hostile is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'BREVITY most nearly means:',
 '["Length","Shortness","Clarity","Complexity"]',
 'Shortness',
 'Brevity means concise and exact use of words; shortness. Shortness is the direct synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'CANDID most nearly means:',
 '["Secretive","Honest","Polite","Cautious"]',
 'Honest',
 'Candid means truthful and straightforward. Honest is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'CAPABLE most nearly means:',
 '["Unable","Willing","Competent","Eager"]',
 'Competent',
 'Capable means having the ability to do something. Competent is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'CAUTIOUS most nearly means:',
 '["Reckless","Careful","Slow","Brave"]',
 'Careful',
 'Cautious means being careful to avoid potential problems or dangers. Careful is the direct synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'CHRONIC most nearly means:',
 '["Acute","Persistent","Severe","Mild"]',
 'Persistent',
 'Chronic describes something that continues for a long time or recurs frequently. Persistent is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'COMPETENT most nearly means:',
 '["Inexperienced","Capable","Enthusiastic","Reliable"]',
 'Capable',
 'Competent means having the necessary ability or skills. Capable is the direct synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'COMPLY most nearly means:',
 '["Resist","Obey","Request","Deny"]',
 'Obey',
 'To comply means to act in accordance with a wish or command. Obey is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'CONCEAL most nearly means:',
 '["Reveal","Hide","Protect","Remove"]',
 'Hide',
 'To conceal means to keep something from being seen or known. Hide is the direct synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'CONDONE most nearly means:',
 '["Punish","Allow","Prevent","Encourage"]',
 'Allow',
 'To condone means to accept or forgive behavior considered wrong. Allow is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'CONFISCATE most nearly means:',
 '["Return","Seize","Purchase","Distribute"]',
 'Seize',
 'To confiscate means to take or seize with authority. Seize is the direct synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'CONSEQUENCE most nearly means:',
 '["Cause","Result","Decision","Action"]',
 'Result',
 'A consequence is a result or effect of an action. Result is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'CONSISTENT most nearly means:',
 '["Irregular","Steady","Variable","Random"]',
 'Steady',
 'Consistent means acting the same way over time; reliable. Steady is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'CONSTRUCT most nearly means:',
 '["Destroy","Build","Plan","Buy"]',
 'Build',
 'To construct means to build or put together. Build is the direct synonym.',
 ARRAY['ASVAB']::TEXT[]),

-- ─────────────────────────────────────────────────
-- BATCH 2: Moderate difficulty (difficulty 2)
-- ─────────────────────────────────────────────────

('Word Knowledge', 2,
 'CONTEMPLATE most nearly means:',
 '["Ignore","Consider","Reject","Finalize"]',
 'Consider',
 'To contemplate means to think carefully about something. Consider is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'CONTINGENT most nearly means:',
 '["Guaranteed","Dependent","Separate","Planned"]',
 'Dependent',
 'Contingent means dependent on circumstances. Dependent is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'CONTRADICT most nearly means:',
 '["Agree with","Deny","Confirm","Question"]',
 'Deny',
 'To contradict means to assert the opposite of. Deny is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'CRUCIAL most nearly means:',
 '["Minor","Essential","Complex","Dangerous"]',
 'Essential',
 'Crucial means extremely important. Essential is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'CUNNING most nearly means:',
 '["Honest","Clever","Aggressive","Weak"]',
 'Clever',
 'Cunning means having or showing skill in achieving goals through deceptive means. Clever is the closest match.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'DEBRIS most nearly means:',
 '["Supplies","Wreckage","Equipment","Materials"]',
 'Wreckage',
 'Debris means scattered pieces of waste or remains. Wreckage is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'DEDUCE most nearly means:',
 '["Guess","Conclude","Ignore","Estimate"]',
 'Conclude',
 'To deduce means to reach a conclusion by reasoning. Conclude is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'DEFICIENT most nearly means:',
 '["Excellent","Lacking","Average","Damaged"]',
 'Lacking',
 'Deficient means not having enough of a specified quality. Lacking is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'DELIBERATE most nearly means:',
 '["Accidental","Intentional","Hasty","Careless"]',
 'Intentional',
 'Deliberate means done consciously and intentionally. Intentional is the direct synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'DEMONSTRATE most nearly means:',
 '["Hide","Show","Explain","Deny"]',
 'Show',
 'To demonstrate means to show or prove something clearly. Show is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'DENSE most nearly means:',
 '["Sparse","Thick","Clear","Hollow"]',
 'Thick',
 'Dense means closely packed together; thick. Thick is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'DETECT most nearly means:',
 '["Create","Discover","Remove","Track"]',
 'Discover',
 'To detect means to discover or notice. Discover is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'DETRIMENTAL most nearly means:',
 '["Helpful","Harmful","Necessary","Neutral"]',
 'Harmful',
 'Detrimental means causing harm or damage. Harmful is the direct synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'DILIGENT most nearly means:',
 '["Lazy","Hardworking","Intelligent","Organized"]',
 'Hardworking',
 'Diligent means having or showing care in work. Hardworking is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'DISCREPANCY most nearly means:',
 '["Agreement","Difference","Error","Mistake"]',
 'Difference',
 'A discrepancy is a lack of compatibility between facts. Difference is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'DISPERSE most nearly means:',
 '["Gather","Scatter","Combine","Move"]',
 'Scatter',
 'To disperse means to distribute or spread over a wide area. Scatter is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'DISTINCTIVE most nearly means:',
 '["Common","Unique","Similar","Plain"]',
 'Unique',
 'Distinctive means clearly different and recognizable. Unique is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'DOMINATE most nearly means:',
 '["Surrender","Control","Follow","Compete"]',
 'Control',
 'To dominate means to have a commanding influence over. Control is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'DURABLE most nearly means:',
 '["Fragile","Sturdy","Heavy","Cheap"]',
 'Sturdy',
 'Durable means able to withstand wear and damage. Sturdy is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'EFFICIENT most nearly means:',
 '["Wasteful","Effective","Expensive","Reliable"]',
 'Effective',
 'Efficient means achieving maximum results with minimum wasted effort. Effective is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

-- ─────────────────────────────────────────────────
-- BATCH 3: Military / technical vocabulary
-- ─────────────────────────────────────────────────

('Word Knowledge', 2,
 'ELIGIBLE most nearly means:',
 '["Disqualified","Qualified","Willing","Selected"]',
 'Qualified',
 'Eligible means satisfying the conditions required. Qualified is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'ELUSIVE most nearly means:',
 '["Obvious","Hard to find","Dangerous","Slow"]',
 'Hard to find',
 'Elusive means difficult to find, catch, or achieve. "Hard to find" is the closest meaning.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'ENFORCE most nearly means:',
 '["Request","Uphold","Remove","Create"]',
 'Uphold',
 'To enforce means to compel compliance with a law or rule. Uphold is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'ESTABLISH most nearly means:',
 '["Destroy","Create","Question","Identify"]',
 'Create',
 'To establish means to set up on a firm or permanent basis. Create is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'EVACUATE most nearly means:',
 '["Enter","Leave","Protect","Secure"]',
 'Leave',
 'To evacuate means to remove from a dangerous place. Leave is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'EXERT most nearly means:',
 '["Reduce","Apply","Withdraw","Increase"]',
 'Apply',
 'To exert means to apply force, influence, or quality. Apply is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'EXHAUSTED most nearly means:',
 '["Energized","Depleted","Bored","Damaged"]',
 'Depleted',
 'Exhausted means completely used up or worn out. Depleted is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'EXPEDITE most nearly means:',
 '["Delay","Accelerate","Plan","Organize"]',
 'Accelerate',
 'To expedite means to make something happen faster. Accelerate is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'EXPLICIT most nearly means:',
 '["Vague","Clear","Implied","Brief"]',
 'Clear',
 'Explicit means stated clearly and directly. Clear is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'FACILITATE most nearly means:',
 '["Complicate","Ease","Prevent","Require"]',
 'Ease',
 'To facilitate means to make an action or process easier. Ease is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'FATAL most nearly means:',
 '["Harmful","Deadly","Serious","Painful"]',
 'Deadly',
 'Fatal means causing death. Deadly is the direct synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'FEASIBLE most nearly means:',
 '["Impossible","Possible","Difficult","Expensive"]',
 'Possible',
 'Feasible means possible and practical to do. Possible is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'FEROCIOUS most nearly means:',
 '["Gentle","Fierce","Loud","Fast"]',
 'Fierce',
 'Ferocious means savagely fierce or cruel. Fierce is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'FLEXIBLE most nearly means:',
 '["Rigid","Adaptable","Strong","Thin"]',
 'Adaptable',
 'Flexible means ready and able to change. Adaptable is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'FORMIDABLE most nearly means:',
 '["Weak","Impressive","Dangerous","Large"]',
 'Impressive',
 'Formidable means inspiring fear or respect through being impressively large or capable. Impressive is the closest match.',
 ARRAY['ASVAB']::TEXT[]),

-- ─────────────────────────────────────────────────
-- BATCH 4: Moderate difficulty continued
-- ─────────────────────────────────────────────────

('Word Knowledge', 2,
 'FORFEIT most nearly means:',
 '["Win","Give up","Compete","Earn"]',
 'Give up',
 'To forfeit means to lose or give something up as a penalty. "Give up" is the closest meaning.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'FRAGMENT most nearly means:',
 '["Whole","Piece","Section","Layer"]',
 'Piece',
 'A fragment is a small part broken off from something. Piece is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'FUNDAMENTAL most nearly means:',
 '["Complex","Basic","Optional","Advanced"]',
 'Basic',
 'Fundamental means forming a necessary base; essential. Basic is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'GENUINE most nearly means:',
 '["Fake","Real","Similar","Approved"]',
 'Real',
 'Genuine means truly what it is said to be; authentic. Real is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'GRAVE most nearly means:',
 '["Minor","Serious","Deep","Dangerous"]',
 'Serious',
 'Grave means giving cause for concern; serious. Serious is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'HAZARDOUS most nearly means:',
 '["Safe","Dangerous","Difficult","Uncertain"]',
 'Dangerous',
 'Hazardous means risky or dangerous. Dangerous is the direct synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'HOSTILE most nearly means:',
 '["Friendly","Unfriendly","Neutral","Cautious"]',
 'Unfriendly',
 'Hostile means showing or feeling opposition. Unfriendly is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'IDENTICAL most nearly means:',
 '["Different","Exactly the same","Very similar","Related"]',
 'Exactly the same',
 'Identical means exactly alike. "Exactly the same" is the closest meaning.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'ILLUMINATE most nearly means:',
 '["Darken","Light up","Describe","Reveal"]',
 'Light up',
 'To illuminate means to light up or make clear. "Light up" is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'IMMINENT most nearly means:',
 '["Distant","About to happen","Possible","Certain"]',
 'About to happen',
 'Imminent means about to happen very soon. "About to happen" captures this meaning.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'IMPEDE most nearly means:',
 '["Assist","Hinder","Ignore","Accelerate"]',
 'Hinder',
 'To impede means to obstruct or delay. Hinder is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'IMPLEMENT most nearly means:',
 '["Plan","Execute","Ignore","Design"]',
 'Execute',
 'To implement means to put into effect. Execute is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'INEVITABLE most nearly means:',
 '["Preventable","Certain to happen","Possible","Unlikely"]',
 'Certain to happen',
 'Inevitable means certain to happen; unavoidable. "Certain to happen" is the closest meaning.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'INFERIOR most nearly means:',
 '["Superior","Lower quality","Cheaper","Weaker"]',
 'Lower quality',
 'Inferior means lower in rank, quality, or importance. "Lower quality" is the closest meaning.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 3,
 'INHERENT most nearly means:',
 '["Acquired","Natural","Obvious","Important"]',
 'Natural',
 'Inherent means existing as a natural or essential part of something. Natural is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

-- ─────────────────────────────────────────────────
-- BATCH 5: Harder vocabulary (difficulty 2-3)
-- ─────────────────────────────────────────────────

('Word Knowledge', 2,
 'INITIATIVE most nearly means:',
 '["Permission","Leadership","Courage","Action"]',
 'Action',
 'Initiative means the ability to take action independently. Action is the closest synonym in this context.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'INSPECT most nearly means:',
 '["Ignore","Examine","Fix","Report"]',
 'Examine',
 'To inspect means to look at closely and critically. Examine is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'INTEGRITY most nearly means:',
 '["Dishonesty","Honesty","Loyalty","Courage"]',
 'Honesty',
 'Integrity means the quality of being honest and having strong moral principles. Honesty is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'INTIMIDATE most nearly means:',
 '["Encourage","Frighten","Persuade","Threaten"]',
 'Frighten',
 'To intimidate means to frighten someone into doing something. Frighten is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 3,
 'INUNDATE most nearly means:',
 '["Drain","Overwhelm","Supply","Delay"]',
 'Overwhelm',
 'To inundate means to overwhelm with a flood of things. Overwhelm is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'JEOPARDIZE most nearly means:',
 '["Protect","Endanger","Monitor","Improve"]',
 'Endanger',
 'To jeopardize means to put into a situation where harm is possible. Endanger is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'JURISDICTION most nearly means:',
 '["Permission","Authority","Territory","Control"]',
 'Authority',
 'Jurisdiction means the official authority to make decisions. Authority is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'KEEN most nearly means:',
 '["Dull","Sharp","Slow","Eager"]',
 'Sharp',
 'Keen means having or showing eagerness or sharpness. Sharp is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'LETHAL most nearly means:',
 '["Harmful","Deadly","Powerful","Painful"]',
 'Deadly',
 'Lethal means sufficient to cause death. Deadly is the direct synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'LUCID most nearly means:',
 '["Confused","Clear","Bright","Simple"]',
 'Clear',
 'Lucid means expressed clearly and easy to understand. Clear is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 3,
 'MAGNITUDE most nearly means:',
 '["Distance","Size","Importance","Intensity"]',
 'Size',
 'Magnitude means the great size or extent of something. Size is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'MANDATORY most nearly means:',
 '["Optional","Required","Suggested","Permitted"]',
 'Required',
 'Mandatory means required by law or rule. Required is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'MAXIMUM most nearly means:',
 '["Minimum","Highest","Average","Limit"]',
 'Highest',
 'Maximum means the greatest possible amount or degree. Highest is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'METICULOUS most nearly means:',
 '["Careless","Careful","Slow","Thorough"]',
 'Careful',
 'Meticulous means showing great attention to detail. Careful is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'MINIMIZE most nearly means:',
 '["Increase","Reduce","Eliminate","Assess"]',
 'Reduce',
 'To minimize means to reduce to the smallest possible amount. Reduce is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

-- ─────────────────────────────────────────────────
-- BATCH 6: Military/technical context vocabulary
-- ─────────────────────────────────────────────────

('Word Knowledge', 2,
 'MOBILIZE most nearly means:',
 '["Disband","Deploy","Train","Equip"]',
 'Deploy',
 'To mobilize means to organize and make ready for action. Deploy is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'MONOTONOUS most nearly means:',
 '["Varied","Boring","Difficult","Quiet"]',
 'Boring',
 'Monotonous means dull and tedious due to lack of variety. Boring is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'NEUTRAL most nearly means:',
 '["Biased","Impartial","Friendly","Inactive"]',
 'Impartial',
 'Neutral means not supporting either side. Impartial is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'NONCHALANT most nearly means:',
 '["Anxious","Casual","Careless","Confident"]',
 'Casual',
 'Nonchalant means feeling or appearing casually calm. Casual is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 3,
 'NOTORIOUS most nearly means:',
 '["Famous","Infamous","Dangerous","Powerful"]',
 'Infamous',
 'Notorious means famous for a bad quality or deed. Infamous is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'OBJECTIVE most nearly means:',
 '["Biased","Unbiased","Clear","Reasonable"]',
 'Unbiased',
 'Objective means not influenced by personal feelings. Unbiased is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'OBSTACLE most nearly means:',
 '["Path","Barrier","Challenge","Delay"]',
 'Barrier',
 'An obstacle is something that blocks a path or progress. Barrier is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'OMINOUS most nearly means:',
 '["Reassuring","Threatening","Powerful","Serious"]',
 'Threatening',
 'Ominous means giving the impression that something bad is going to happen. Threatening is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'OMIT most nearly means:',
 '["Include","Leave out","Forget","Skip"]',
 'Leave out',
 'To omit means to leave out or exclude. "Leave out" is the closest meaning.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'OPTIMAL most nearly means:',
 '["Average","Best","Sufficient","Practical"]',
 'Best',
 'Optimal means best or most favorable. Best is the direct synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'PARAMOUNT most nearly means:',
 '["Minor","Most important","Large","Final"]',
 'Most important',
 'Paramount means more important than anything else. "Most important" is the closest meaning.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'PERCEIVE most nearly means:',
 '["Ignore","Notice","Assume","Judge"]',
 'Notice',
 'To perceive means to become aware of something through the senses. Notice is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 3,
 'PERILOUS most nearly means:',
 '["Safe","Dangerous","Difficult","Challenging"]',
 'Dangerous',
 'Perilous means full of danger or risk. Dangerous is the direct synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'PERSISTENT most nearly means:',
 '["Occasional","Continuing","Stubborn","Aggressive"]',
 'Continuing',
 'Persistent means continuing firmly despite difficulty. Continuing is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'PRECISE most nearly means:',
 '["Approximate","Exact","Careful","Correct"]',
 'Exact',
 'Precise means marked by exactness. Exact is the direct synonym.',
 ARRAY['ASVAB']::TEXT[]),

-- ─────────────────────────────────────────────────
-- BATCH 7: Advanced vocabulary (difficulty 2-3)
-- ─────────────────────────────────────────────────

('Word Knowledge', 2,
 'PREVALENT most nearly means:',
 '["Rare","Common","Powerful","Obvious"]',
 'Common',
 'Prevalent means widespread in a particular area at a particular time. Common is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 3,
 'PROFICIENT most nearly means:',
 '["Beginner","Skilled","Trained","Experienced"]',
 'Skilled',
 'Proficient means competent or skilled. Skilled is the direct synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'PROHIBIT most nearly means:',
 '["Allow","Forbid","Regulate","Punish"]',
 'Forbid',
 'To prohibit means to formally forbid by law or rule. Forbid is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'PROMINENT most nearly means:',
 '["Unknown","Well-known","Powerful","Visible"]',
 'Well-known',
 'Prominent means important or famous. "Well-known" is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 3,
 'PRUDENT most nearly means:',
 '["Reckless","Cautious","Honest","Clever"]',
 'Cautious',
 'Prudent means acting with care and thought for the future. Cautious is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'RATION most nearly means:',
 '["Increase","Allowance","Supply","Reduce"]',
 'Allowance',
 'A ration is a fixed allowance of food or goods. Allowance is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'REINFORCE most nearly means:',
 '["Weaken","Strengthen","Replace","Protect"]',
 'Strengthen',
 'To reinforce means to add strength or support. Strengthen is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'RELEVANT most nearly means:',
 '["Unrelated","Applicable","Important","Necessary"]',
 'Applicable',
 'Relevant means closely connected to the matter at hand. Applicable is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'RELUCTANT most nearly means:',
 '["Eager","Unwilling","Hesitant","Forced"]',
 'Unwilling',
 'Reluctant means not willing to do something. Unwilling is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 3,
 'RESILIENT most nearly means:',
 '["Fragile","Tough","Flexible","Strong"]',
 'Tough',
 'Resilient means able to withstand or recover from difficult conditions. Tough is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'RETRIEVE most nearly means:',
 '["Lose","Get back","Store","Locate"]',
 'Get back',
 'To retrieve means to get back or recover. "Get back" is the closest meaning.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'RIGID most nearly means:',
 '["Flexible","Stiff","Strong","Heavy"]',
 'Stiff',
 'Rigid means unable to bend; stiff. Stiff is the direct synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'SCRUTINIZE most nearly means:',
 '["Ignore","Examine closely","Approve","Monitor"]',
 'Examine closely',
 'To scrutinize means to examine carefully. "Examine closely" is the closest meaning.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'SEQUENCE most nearly means:',
 '["Random","Order","Process","Pattern"]',
 'Order',
 'A sequence is a particular order in which things follow each other. Order is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 3,
 'SHREWD most nearly means:',
 '["Foolish","Clever","Greedy","Suspicious"]',
 'Clever',
 'Shrewd means having sharp powers of judgment; clever. Clever is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

-- ─────────────────────────────────────────────────
-- BATCH 8: Context clue / sentence format questions
-- ─────────────────────────────────────────────────

('Word Knowledge', 2,
 'SIGNIFICANT most nearly means:',
 '["Minor","Important","Large","Noticeable"]',
 'Important',
 'Significant means sufficiently great or important. Important is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'SIMULATE most nearly means:',
 '["Perform","Imitate","Practice","Create"]',
 'Imitate',
 'To simulate means to imitate the appearance or character of. Imitate is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'SKEPTICAL most nearly means:',
 '["Trusting","Doubtful","Cautious","Curious"]',
 'Doubtful',
 'Skeptical means not easily convinced; doubtful. Doubtful is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'SPARSE most nearly means:',
 '["Dense","Thin","Empty","Small"]',
 'Thin',
 'Sparse means thinly distributed or scattered. Thin is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'SPECIFIC most nearly means:',
 '["General","Exact","Clear","Detailed"]',
 'Exact',
 'Specific means clearly defined or identified. Exact is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 3,
 'SPONTANEOUS most nearly means:',
 '["Planned","Unplanned","Natural","Impulsive"]',
 'Unplanned',
 'Spontaneous means performed without planning. Unplanned is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'STABLE most nearly means:',
 '["Unstable","Steady","Strong","Fixed"]',
 'Steady',
 'Stable means not likely to change or fail. Steady is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'SUBORDINATE most nearly means:',
 '["Superior","Lower-ranking","Assistant","Follower"]',
 'Lower-ranking',
 'Subordinate means lower in rank or position. "Lower-ranking" is the closest meaning.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 3,
 'SUCCINCT most nearly means:',
 '["Lengthy","Brief","Clear","Organized"]',
 'Brief',
 'Succinct means briefly and clearly expressed. Brief is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'SUFFICIENT most nearly means:',
 '["Inadequate","Enough","Plenty","Satisfactory"]',
 'Enough',
 'Sufficient means as much as is needed. Enough is the direct synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'SUPPRESS most nearly means:',
 '["Release","Stop","Reduce","Control"]',
 'Stop',
 'To suppress means to prevent from being known or felt. Stop is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 3,
 'SURVEILLANCE most nearly means:',
 '["Protection","Monitoring","Investigation","Security"]',
 'Monitoring',
 'Surveillance means close observation, especially of a suspected person. Monitoring is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'SUSTAIN most nearly means:',
 '["Destroy","Maintain","Support","Extend"]',
 'Maintain',
 'To sustain means to keep going over time. Maintain is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'SYSTEMATIC most nearly means:',
 '["Random","Organized","Thorough","Logical"]',
 'Organized',
 'Systematic means done according to a fixed plan. Organized is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 3,
 'TENACIOUS most nearly means:',
 '["Weak","Persistent","Stubborn","Brave"]',
 'Persistent',
 'Tenacious means tending to keep a firm hold; persistent. Persistent is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

-- ─────────────────────────────────────────────────
-- BATCH 9: Final set — high-frequency ASVAB words
-- ─────────────────────────────────────────────────

('Word Knowledge', 1,
 'TERMINATE most nearly means:',
 '["Begin","End","Suspend","Delay"]',
 'End',
 'To terminate means to bring to an end. End is the direct synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'TOXIC most nearly means:',
 '["Harmless","Poisonous","Dangerous","Chemical"]',
 'Poisonous',
 'Toxic means poisonous. Poisonous is the direct synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'TRANQUIL most nearly means:',
 '["Loud","Peaceful","Calm","Silent"]',
 'Peaceful',
 'Tranquil means free from disturbance. Peaceful is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 3,
 'TRANSPARENT most nearly means:',
 '["Hidden","Clear","Honest","Thin"]',
 'Clear',
 'Transparent means able to be seen through or understood. Clear is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'UNDERMINE most nearly means:',
 '["Support","Weaken","Damage","Threaten"]',
 'Weaken',
 'To undermine means to weaken gradually. Weaken is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'UNIFORM most nearly means:',
 '["Variable","Consistent","Standard","Equal"]',
 'Consistent',
 'Uniform means remaining the same in all cases. Consistent is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'VALIDATE most nearly means:',
 '["Reject","Confirm","Approve","Test"]',
 'Confirm',
 'To validate means to check or prove the validity of. Confirm is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 3,
 'VERSATILE most nearly means:',
 '["Specialized","Adaptable","Skilled","Useful"]',
 'Adaptable',
 'Versatile means able to adapt to many different functions. Adaptable is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'VIGILANT most nearly means:',
 '["Careless","Alert","Careful","Cautious"]',
 'Alert',
 'Vigilant means keeping careful watch for possible danger. Alert is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'VOLATILE most nearly means:',
 '["Stable","Unstable","Explosive","Changing"]',
 'Unstable',
 'Volatile means liable to change rapidly and unpredictably. Unstable is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 3,
 'WARY most nearly means:',
 '["Trusting","Cautious","Suspicious","Careful"]',
 'Cautious',
 'Wary means feeling or showing caution about possible dangers. Cautious is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 2,
 'WITHSTAND most nearly means:',
 '["Yield to","Endure","Resist","Survive"]',
 'Endure',
 'To withstand means to remain undamaged or unaffected by. Endure is the closest synonym.',
 ARRAY['ASVAB']::TEXT[]),

('Word Knowledge', 1,
 'ZENITH most nearly means:',
 '["Lowest point","Highest point","Middle","End"]',
 'Highest point',
 'Zenith means the highest point reached. "Highest point" is the closest meaning.',
 ARRAY['ASVAB']::TEXT[]);

END $$;
