#!/usr/bin/env python3
"""
OAR Pro v4 — Content Migration Script
Extracts lessons and questions from current HTML files
and generates SQL INSERT statements for Supabase.

Usage: python3 migrate_content.py > 003_seed_content.sql
"""

import re
import json
import html

# Paths to current HTML files
import os
_dir = os.path.dirname(os.path.abspath(__file__))
_root = os.path.join(_dir, '..', '..', '..')
STUDY_HTML = os.path.join(_root, "study.html")
PRACTICE_HTML = os.path.join(_root, "practice.html")

def extract_lessons(filepath):
    """Extract lesson objects from study.html's JavaScript lessons array."""
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    # Find the lessons array
    # Pattern: { id: N, section: "...", title: "...", desc: "...", tags: [...], content: `...` }
    lessons = []

    # Use regex to find each lesson object
    pattern = r'\{\s*id:\s*(\d+),\s*section:\s*"([^"]+)",\s*title:\s*"([^"]+)",\s*desc:\s*"([^"]*)",\s*tags:\s*\[([^\]]*)\],\s*content:\s*`(.*?)`\s*\}'

    matches = re.finditer(pattern, content, re.DOTALL)

    for match in matches:
        lesson_id = int(match.group(1))
        section = match.group(2)
        title = match.group(3)
        desc = match.group(4)
        tags_raw = match.group(5)
        content_html = match.group(6).strip()

        # Parse tags
        tags = [t.strip().strip('"').strip("'") for t in tags_raw.split(',') if t.strip()]

        lessons.append({
            'id': lesson_id,
            'section': section,
            'title': title,
            'description': desc,
            'tags': tags,
            'content_html': content_html,
            'sort_order': lesson_id
        })

    return lessons


def extract_questions(filepath):
    """Extract question objects from practice.html's JavaScript questions array."""
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    questions = []

    # Pattern for questions: {id:"XX",section:"...",topic:"...",q:"...",passage:null,options:[...],correct:N,explanation:"..."}
    pattern = r'\{id:"([^"]+)",section:"([^"]+)",topic:"([^"]+)",q:"((?:[^"\\]|\\.)*)",passage:(null|"(?:[^"\\]|\\.)*"),options:\[([^\]]+)\],correct:(\d+),explanation:"((?:[^"\\]|\\.)*)"\}'

    matches = re.finditer(pattern, content)

    for match in matches:
        q_id = match.group(1)
        section = match.group(2)
        topic = match.group(3)
        question_text = match.group(4).replace('\\"', '"').replace("\\'", "'")
        passage_raw = match.group(5)
        options_raw = match.group(6)
        correct = int(match.group(7))
        explanation = match.group(8).replace('\\"', '"').replace("\\'", "'")

        # Parse passage
        passage = None if passage_raw == 'null' else passage_raw.strip('"').replace('\\"', '"')

        # Parse options
        options = [o.strip().strip('"').replace('\\"', '"') for o in options_raw.split('","')]
        # Clean up first and last
        if options:
            options[0] = options[0].lstrip('"')
            options[-1] = options[-1].rstrip('"')

        questions.append({
            'id': q_id,
            'section': section,
            'topic': topic,
            'question_text': question_text,
            'passage': passage,
            'options': options,
            'correct_index': correct,
            'explanation': explanation,
            'difficulty': 2  # default medium
        })

    return questions


def escape_sql(s):
    """Escape a string for SQL insertion."""
    if s is None:
        return 'NULL'
    return "'" + s.replace("'", "''").replace("\\", "\\\\") + "'"


def generate_sql(lessons, questions):
    """Generate SQL INSERT statements."""
    lines = []
    lines.append("-- OAR Pro v4 — Seed Content")
    lines.append("-- Auto-generated by migrate_content.py")
    lines.append(f"-- {len(lessons)} lessons, {len(questions)} questions")
    lines.append("")

    # Lessons
    lines.append("-- ============================================")
    lines.append("-- LESSONS")
    lines.append("-- ============================================")
    for lesson in lessons:
        tags_sql = "ARRAY[" + ",".join(escape_sql(t) for t in lesson['tags']) + "]" if lesson['tags'] else "ARRAY[]::TEXT[]"
        lines.append(f"""INSERT INTO lessons (id, section, title, description, tags, content_html, sort_order)
VALUES ({lesson['id']}, {escape_sql(lesson['section'])}, {escape_sql(lesson['title'])}, {escape_sql(lesson['description'])}, {tags_sql}, {escape_sql(lesson['content_html'])}, {lesson['sort_order']})
ON CONFLICT (id) DO UPDATE SET content_html = EXCLUDED.content_html, title = EXCLUDED.title;
""")

    # Questions
    lines.append("-- ============================================")
    lines.append("-- QUESTIONS")
    lines.append("-- ============================================")
    for q in questions:
        options_sql = "ARRAY[" + ",".join(escape_sql(o) for o in q['options']) + "]"
        passage_sql = escape_sql(q['passage']) if q['passage'] else 'NULL'
        lines.append(f"""INSERT INTO questions (id, section, topic, question_text, passage, options, correct_index, explanation, difficulty)
VALUES ({escape_sql(q['id'])}, {escape_sql(q['section'])}, {escape_sql(q['topic'])}, {escape_sql(q['question_text'])}, {passage_sql}, {options_sql}, {q['correct_index']}, {escape_sql(q['explanation'])}, {q['difficulty']})
ON CONFLICT (id) DO UPDATE SET question_text = EXCLUDED.question_text, explanation = EXCLUDED.explanation;
""")

    return "\n".join(lines)


if __name__ == "__main__":
    print("-- Extracting lessons from study.html...")
    lessons = extract_lessons(STUDY_HTML)
    print(f"-- Found {len(lessons)} lessons", flush=True)

    print("-- Extracting questions from practice.html...")
    questions = extract_questions(PRACTICE_HTML)
    print(f"-- Found {len(questions)} questions", flush=True)

    sql = generate_sql(lessons, questions)

    # Write to file
    output_path = "003_seed_content.sql"
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(sql)

    print(f"-- Written to {output_path}")
    print(f"-- Total: {len(lessons)} lessons + {len(questions)} questions")
