#!/usr/bin/env python3
"""Electronics Information questions — 75 questions"""

EI_QUESTIONS = [
    # === OHM'S LAW (V=IR) ===
    {"id": "EI001", "section": "Electronics Information", "topic": "Ohm's Law", "question_text": "Ohm's Law states the relationship between voltage (V), current (I), and resistance (R). Which formula correctly expresses this?", "options": ["V = I + R", "V = I × R", "V = I / R", "V = R / I"], "correct_index": 1, "difficulty": 1, "explanation": "Ohm's Law: V = IR (Voltage = Current × Resistance). Rearranged: I = V/R and R = V/I. If voltage increases and resistance stays the same, current increases proportionally.", "test_types": ["ASVAB"]},
    {"id": "EI002", "section": "Electronics Information", "topic": "Ohm's Law", "question_text": "A circuit has a voltage of 12V and a resistance of 4 ohms. What is the current?", "options": ["48 amps", "8 amps", "3 amps", "0.33 amps"], "correct_index": 2, "difficulty": 1, "explanation": "Using I = V/R: I = 12V ÷ 4Ω = 3 amps. Check: V = IR = 3 × 4 = 12V. Current is measured in amperes (amps, A).", "test_types": ["ASVAB"]},
    {"id": "EI003", "section": "Electronics Information", "topic": "Ohm's Law", "question_text": "A 6-ohm resistor carries 2 amps of current. What is the voltage across it?", "options": ["3V", "4V", "8V", "12V"], "correct_index": 3, "difficulty": 1, "explanation": "V = IR = 2A × 6Ω = 12V. Voltage is the 'pressure' pushing current through the resistance.", "test_types": ["ASVAB"]},
    {"id": "EI004", "section": "Electronics Information", "topic": "Ohm's Law", "question_text": "If voltage stays constant and resistance doubles, current will:", "options": ["Double", "Stay the same", "Decrease by half", "Increase by half"], "correct_index": 2, "difficulty": 2, "explanation": "From I = V/R, if R doubles while V is constant, I = V/(2R) — the current is halved. Current and resistance are inversely proportional when voltage is constant.", "test_types": ["ASVAB"]},

    # === POWER (P = IV) ===
    {"id": "EI005", "section": "Electronics Information", "topic": "Power", "question_text": "The formula for electrical power is:", "options": ["P = V + I", "P = V / I", "P = V × I", "P = V - I"], "correct_index": 2, "difficulty": 1, "explanation": "Power (P) = Voltage (V) × Current (I). Power is measured in watts (W). Combined with Ohm's Law: P = I²R or P = V²/R.", "test_types": ["ASVAB"]},
    {"id": "EI006", "section": "Electronics Information", "topic": "Power", "question_text": "A circuit operates at 120V and draws 5 amps. What is the power consumed?", "options": ["24W", "115W", "600W", "125W"], "correct_index": 2, "difficulty": 1, "explanation": "P = V × I = 120V × 5A = 600W (600 watts). This is equivalent to a large home appliance like a microwave.", "test_types": ["ASVAB"]},
    {"id": "EI007", "section": "Electronics Information", "topic": "Power", "question_text": "A 100-ohm resistor carries 2 amps. Using P = I²R, what is the power dissipated?", "options": ["200W", "400W", "50W", "10,000W"], "correct_index": 1, "difficulty": 2, "explanation": "P = I²R = (2)² × 100 = 4 × 100 = 400W. This formula is useful when you know current and resistance but not voltage.", "test_types": ["ASVAB"]},
    {"id": "EI008", "section": "Electronics Information", "topic": "Power", "question_text": "Using P = V²/R, what power is dissipated by a 50-ohm resistor with 10V across it?", "options": ["500W", "5W", "2W", "0.5W"], "correct_index": 2, "difficulty": 2, "explanation": "P = V²/R = (10)²/50 = 100/50 = 2W. This formula is useful when you know voltage and resistance but not current.", "test_types": ["ASVAB"]},

    # === SERIES CIRCUITS ===
    {"id": "EI009", "section": "Electronics Information", "topic": "Series Circuits", "question_text": "In a series circuit, current:", "options": ["Divides among branches", "Is the same through all components", "Increases with each resistor", "Decreases after each component"], "correct_index": 1, "difficulty": 1, "explanation": "In a series circuit, there is only one path for current. Therefore, the same current flows through every component. Voltage drops across each component, but current remains constant.", "test_types": ["ASVAB"]},
    {"id": "EI010", "section": "Electronics Information", "topic": "Series Circuits", "question_text": "Three resistors of 4Ω, 6Ω, and 10Ω are connected in series. What is the total resistance?", "options": ["2.0Ω", "6.67Ω", "20Ω", "240Ω"], "correct_index": 2, "difficulty": 1, "explanation": "In series: R_total = R1 + R2 + R3 = 4 + 6 + 10 = 20Ω. Total resistance in series always increases — it equals the sum of all resistors.", "test_types": ["ASVAB"]},
    {"id": "EI011", "section": "Electronics Information", "topic": "Series Circuits", "question_text": "In a series circuit with a 12V battery and three equal resistors, how does the voltage distribute?", "options": ["All 12V drops across the first resistor", "12V distributes equally across all three", "Each resistor gets 12V", "Voltage does not change in a series circuit"], "correct_index": 1, "difficulty": 2, "explanation": "In a series circuit, the total voltage divides across the resistors in proportion to their resistance. For three equal resistors, 12V ÷ 3 = 4V across each. Total voltage = sum of all drops.", "test_types": ["ASVAB"]},
    {"id": "EI012", "section": "Electronics Information", "topic": "Series Circuits", "question_text": "If one bulb burns out in a series circuit of three bulbs, what happens?", "options": ["The other two bulbs get brighter", "The other two bulbs stay the same", "The other two bulbs go out too", "Only one remaining bulb goes out"], "correct_index": 2, "difficulty": 1, "explanation": "In a series circuit, current has only one path. If one component fails (open circuit), the circuit is broken and no current flows — all components stop working. Old Christmas lights wired in series had this problem.", "test_types": ["ASVAB"]},

    # === PARALLEL CIRCUITS ===
    {"id": "EI013", "section": "Electronics Information", "topic": "Parallel Circuits", "question_text": "In a parallel circuit, voltage:", "options": ["Divides among all branches", "Is different in each branch", "Is the same across all branches", "Increases with each branch"], "correct_index": 2, "difficulty": 1, "explanation": "In a parallel circuit, all branches connect directly to the voltage source, so each branch has the same voltage. Current divides based on each branch's resistance.", "test_types": ["ASVAB"]},
    {"id": "EI014", "section": "Electronics Information", "topic": "Parallel Circuits", "question_text": "Two resistors of 6Ω each are connected in parallel. What is the total resistance?", "options": ["12Ω", "6Ω", "3Ω", "1.5Ω"], "correct_index": 2, "difficulty": 2, "explanation": "For two equal resistors in parallel: R_total = R/2 = 6/2 = 3Ω. Using the formula 1/R_total = 1/6 + 1/6 = 2/6, so R_total = 3Ω. Parallel resistance is always less than the smallest resistor.", "test_types": ["ASVAB"]},
    {"id": "EI015", "section": "Electronics Information", "topic": "Parallel Circuits", "question_text": "Adding more resistors in parallel to a circuit will:", "options": ["Increase total resistance", "Decrease total resistance", "Keep total resistance the same", "Double total resistance"], "correct_index": 1, "difficulty": 2, "explanation": "Adding resistors in parallel provides more paths for current, which decreases total resistance. This is opposite to series circuits where adding resistors increases resistance.", "test_types": ["ASVAB"]},
    {"id": "EI016", "section": "Electronics Information", "topic": "Parallel Circuits", "question_text": "Household electrical outlets are wired in parallel because:", "options": ["It uses less wire", "Each device gets full voltage and devices work independently", "It increases resistance for safety", "Parallel circuits use less current"], "correct_index": 1, "difficulty": 2, "explanation": "Parallel wiring ensures each outlet gets full voltage (120V) and that unplugging or losing one device doesn't affect others. Series wiring would drop voltage and one failure would kill everything.", "test_types": ["ASVAB"]},

    # === CONDUCTORS / INSULATORS / SEMICONDUCTORS ===
    {"id": "EI017", "section": "Electronics Information", "topic": "Conductors and Insulators", "question_text": "Which material is the best electrical conductor?", "options": ["Rubber", "Glass", "Copper", "Silicon"], "correct_index": 2, "difficulty": 1, "explanation": "Copper is an excellent conductor with very low resistance. It is the most common wire material. Rubber and glass are insulators. Silicon is a semiconductor used in transistors and chips.", "test_types": ["ASVAB"]},
    {"id": "EI018", "section": "Electronics Information", "topic": "Conductors and Insulators", "question_text": "Semiconductors differ from conductors in that semiconductors:", "options": ["Always block current completely", "Conduct electricity better than metals", "Have conductivity between conductors and insulators, controllable by conditions", "Only conduct AC current"], "correct_index": 2, "difficulty": 2, "explanation": "Semiconductors (silicon, germanium) have conductivity between conductors and insulators. Their conductivity can be controlled by temperature, light, or impurities (doping), making them ideal for transistors and diodes.", "test_types": ["ASVAB"]},
    {"id": "EI019", "section": "Electronics Information", "topic": "Conductors and Insulators", "question_text": "Which of the following is an electrical insulator?", "options": ["Aluminum", "Carbon", "Rubber", "Mercury"], "correct_index": 2, "difficulty": 1, "explanation": "Rubber is an excellent insulator — it resists electrical current flow. Aluminum and carbon are conductors. Mercury is a liquid metal and a conductor.", "test_types": ["ASVAB"]},

    # === DIODES ===
    {"id": "EI020", "section": "Electronics Information", "topic": "Diodes", "question_text": "A diode allows current to flow:", "options": ["In both directions equally", "Only in one direction (forward bias)", "Only when AC voltage is applied", "In neither direction by default"], "correct_index": 1, "difficulty": 1, "explanation": "A diode is a one-way valve for electrical current. It allows current when forward biased (anode positive, cathode negative) and blocks current when reverse biased. This is used to convert AC to DC (rectification).", "test_types": ["ASVAB"]},
    {"id": "EI021", "section": "Electronics Information", "topic": "Diodes", "question_text": "The process of converting AC (alternating current) to DC (direct current) using diodes is called:", "options": ["Amplification", "Induction", "Rectification", "Modulation"], "correct_index": 2, "difficulty": 2, "explanation": "Rectification converts AC to DC using diodes. A half-wave rectifier uses one diode. A full-wave bridge rectifier uses four diodes to use both halves of the AC cycle.", "test_types": ["ASVAB"]},
    {"id": "EI022", "section": "Electronics Information", "topic": "Diodes", "question_text": "On a diode symbol, current flows from:", "options": ["Cathode to anode", "Anode to cathode", "Either direction depending on voltage", "Ground to positive terminal"], "correct_index": 1, "difficulty": 2, "explanation": "Conventional current flows from anode (positive terminal, triangle base) to cathode (negative terminal, triangle tip/bar). The diode symbol arrow points in the direction current can flow.", "test_types": ["ASVAB"]},

    # === TRANSISTORS ===
    {"id": "EI023", "section": "Electronics Information", "topic": "Transistors", "question_text": "A transistor can function as a:", "options": ["Power source only", "Switch or amplifier", "Capacitor replacement", "Transformer substitute"], "correct_index": 1, "difficulty": 1, "explanation": "Transistors have two key uses: as a switch (on/off for digital logic) and as an amplifier (small input signal controls large output signal). They are the fundamental building block of all modern electronics.", "test_types": ["ASVAB"]},
    {"id": "EI024", "section": "Electronics Information", "topic": "Transistors", "question_text": "A bipolar junction transistor (BJT) has three terminals called:", "options": ["Source, gate, drain", "Anode, cathode, control", "Base, emitter, collector", "Input, output, ground"], "correct_index": 2, "difficulty": 2, "explanation": "A BJT has three terminals: base (the control input), emitter (usually the output), and collector (where current flows into). A small base current controls a much larger collector-emitter current.", "test_types": ["ASVAB"]},
    {"id": "EI025", "section": "Electronics Information", "topic": "Transistors", "question_text": "In an NPN transistor, the collector-emitter current flows when:", "options": ["The base has no connection", "A small positive voltage is applied to the base", "A negative voltage is applied to the collector", "AC current is applied"], "correct_index": 1, "difficulty": 2, "explanation": "In an NPN transistor, applying a small positive voltage to the base allows large current to flow from collector to emitter. PNP transistors use negative base voltage. This is transistor switching action.", "test_types": ["ASVAB"]},

    # === CAPACITORS ===
    {"id": "EI026", "section": "Electronics Information", "topic": "Capacitors", "question_text": "A capacitor stores energy in:", "options": ["A magnetic field", "An electric field between its plates", "Chemical bonds", "Mechanical rotation"], "correct_index": 1, "difficulty": 1, "explanation": "A capacitor stores energy in the electric field between two conductive plates separated by an insulator (dielectric). Inductors store energy in a magnetic field. Batteries store chemical energy.", "test_types": ["ASVAB"]},
    {"id": "EI027", "section": "Electronics Information", "topic": "Capacitors", "question_text": "Capacitance is measured in:", "options": ["Ohms", "Henrys", "Farads", "Watts"], "correct_index": 2, "difficulty": 1, "explanation": "Capacitance is measured in farads (F). Most practical capacitors are microfarads (μF) or picofarads (pF). Ohms measure resistance. Henrys measure inductance. Watts measure power.", "test_types": ["ASVAB"]},
    {"id": "EI028", "section": "Electronics Information", "topic": "Capacitors", "question_text": "A capacitor in a DC circuit will:", "options": ["Conduct current continuously", "Charge up and then block DC current", "Act as a resistor", "Convert DC to AC"], "correct_index": 1, "difficulty": 2, "explanation": "A capacitor charges up to the supply voltage and then blocks DC current (the capacitor is fully charged, no more current flows). In AC circuits, the constantly changing voltage means the capacitor continuously charges and discharges, effectively passing AC.", "test_types": ["ASVAB"]},
    {"id": "EI029", "section": "Electronics Information", "topic": "Capacitors", "question_text": "Capacitors connected in parallel:", "options": ["Have the same total as in series", "Subtract from each other", "Add together (C_total = C1 + C2 + ...)", "Halve the total capacitance"], "correct_index": 2, "difficulty": 2, "explanation": "Capacitors in parallel add directly: C_total = C1 + C2 + C3. This is the opposite of resistors in parallel. Capacitors in series use the reciprocal formula (like resistors in parallel).", "test_types": ["ASVAB"]},

    # === INDUCTORS ===
    {"id": "EI030", "section": "Electronics Information", "topic": "Inductors", "question_text": "An inductor stores energy in:", "options": ["An electric field", "A chemical reaction", "A magnetic field", "Mechanical vibration"], "correct_index": 2, "difficulty": 1, "explanation": "An inductor (a coil of wire) stores energy in the magnetic field created by current flowing through it. Capacitors store energy in an electric field. The magnetic field collapses when current stops, releasing stored energy.", "test_types": ["ASVAB"]},
    {"id": "EI031", "section": "Electronics Information", "topic": "Inductors", "question_text": "Inductance is measured in:", "options": ["Farads", "Ohms", "Watts", "Henrys"], "correct_index": 3, "difficulty": 1, "explanation": "Inductance is measured in henrys (H), named after Joseph Henry. Most practical inductors are millihenrys (mH) or microhenrys (μH). Farads measure capacitance.", "test_types": ["ASVAB"]},
    {"id": "EI032", "section": "Electronics Information", "topic": "Inductors", "question_text": "An inductor opposes:", "options": ["Constant (steady) current", "Changes in current", "High voltages only", "Reverse current"], "correct_index": 1, "difficulty": 2, "explanation": "An inductor opposes changes in current (by Lenz's law). When current tries to increase, the inductor creates a back-EMF opposing the increase. When current tries to decrease, it tries to maintain current. This is why inductors are used in filters.", "test_types": ["ASVAB"]},

    # === AC vs DC ===
    {"id": "EI033", "section": "Electronics Information", "topic": "AC vs DC", "question_text": "AC (alternating current) differs from DC (direct current) in that AC:", "options": ["Has higher voltage", "Only flows in one direction", "Reverses direction periodically", "Cannot be used in motors"], "correct_index": 2, "difficulty": 1, "explanation": "AC reverses its direction of flow periodically (60 times per second at 60 Hz in the US). DC flows in one direction only. AC is used for power distribution because it can be stepped up/down with transformers.", "test_types": ["ASVAB"]},
    {"id": "EI034", "section": "Electronics Information", "topic": "AC vs DC", "question_text": "The standard US household AC frequency is:", "options": ["50 Hz", "60 Hz", "100 Hz", "120 Hz"], "correct_index": 1, "difficulty": 2, "explanation": "US household AC operates at 60 Hz (60 cycles per second). Europe and many other countries use 50 Hz. The 120V refers to voltage, not frequency. The frequency determines how fast current alternates direction.", "test_types": ["ASVAB"]},

    # === FREQUENCY / PERIOD ===
    {"id": "EI035", "section": "Electronics Information", "topic": "Frequency and Period", "question_text": "If a signal has a frequency of 100 Hz, what is its period?", "options": ["100 seconds", "10 seconds", "0.01 seconds", "0.001 seconds"], "correct_index": 2, "difficulty": 2, "explanation": "Period (T) = 1 / frequency (f). T = 1/100 Hz = 0.01 seconds (10 milliseconds). Frequency and period are reciprocals — higher frequency means shorter period.", "test_types": ["ASVAB"]},
    {"id": "EI036", "section": "Electronics Information", "topic": "Frequency and Period", "question_text": "Frequency is measured in:", "options": ["Seconds", "Hertz", "Volts", "Cycles"], "correct_index": 1, "difficulty": 1, "explanation": "Frequency is measured in hertz (Hz), named after Heinrich Hertz. 1 Hz = 1 cycle per second. Kilohertz (kHz) = 1,000 Hz. Megahertz (MHz) = 1,000,000 Hz.", "test_types": ["ASVAB"]},

    # === TRANSFORMERS ===
    {"id": "EI037", "section": "Electronics Information", "topic": "Transformers", "question_text": "A transformer can only work with:", "options": ["DC (direct current)", "AC (alternating current)", "Both AC and DC equally", "High voltage only"], "correct_index": 1, "difficulty": 1, "explanation": "Transformers work only with AC because they rely on a changing magnetic field to induce voltage. DC doesn't change, so it creates a constant field that induces no voltage in the secondary coil.", "test_types": ["ASVAB"]},
    {"id": "EI038", "section": "Electronics Information", "topic": "Transformers", "question_text": "A step-up transformer has 100 turns on the primary and 1,000 turns on the secondary. If 120V is applied, what is the output voltage?", "options": ["12V", "120V", "1,200V", "10,000V"], "correct_index": 2, "difficulty": 2, "explanation": "Vs/Vp = Ns/Np, so Vs = Vp × (Ns/Np) = 120 × (1000/100) = 1,200V. More turns on the secondary = step-up transformer (increases voltage, decreases current).", "test_types": ["ASVAB"]},
    {"id": "EI039", "section": "Electronics Information", "topic": "Transformers", "question_text": "A step-down transformer is used to:", "options": ["Increase voltage and increase current", "Decrease voltage and increase current", "Decrease both voltage and current", "Increase voltage and decrease current"], "correct_index": 1, "difficulty": 2, "explanation": "A step-down transformer decreases voltage and increases current (power stays nearly constant: P = VI). Wall adapters for electronics are step-down transformers reducing 120V AC to lower voltages.", "test_types": ["ASVAB"]},

    # === RESISTOR COLOR CODE ===
    {"id": "EI040", "section": "Electronics Information", "topic": "Resistor Color Code", "question_text": "The resistor color code assigns a number to each color. What number does the color RED represent?", "options": ["1", "2", "3", "4"], "correct_index": 1, "difficulty": 2, "explanation": "Resistor color code: Black=0, Brown=1, Red=2, Orange=3, Yellow=4, Green=5, Blue=6, Violet=7, Gray=8, White=9. Mnemonic: 'BB ROY of Great Britain has a Very Good Wife' (Black, Brown, Red, Orange, Yellow, Green, Blue, Violet, Gray, White).", "test_types": ["ASVAB"]},
    {"id": "EI041", "section": "Electronics Information", "topic": "Resistor Color Code", "question_text": "A resistor has bands: Yellow, Violet, Red. What is its value?", "options": ["472 ohms", "4,700 ohms", "47,000 ohms", "470 ohms"], "correct_index": 1, "difficulty": 3, "explanation": "Yellow=4, Violet=7, Red=multiplier of 100 (10²). Value = 47 × 100 = 4,700 ohms (4.7 kΩ). The first two bands give digits, the third gives the multiplier (power of 10).", "test_types": ["ASVAB"]},
    {"id": "EI042", "section": "Electronics Information", "topic": "Resistor Color Code", "question_text": "In a resistor color code, what does the BROWN band (fourth band) in a precision resistor indicate?", "options": ["The multiplier", "A tolerance of ±1%", "A tolerance of ±5%", "The first digit"], "correct_index": 1, "difficulty": 3, "explanation": "In a 4-band resistor, the fourth band indicates tolerance. Brown = ±1%, Red = ±2%, Gold = ±5%, Silver = ±10%. Tighter tolerance means the actual value is closer to the marked value.", "test_types": ["ASVAB"]},

    # === FUSES and CIRCUIT BREAKERS ===
    {"id": "EI043", "section": "Electronics Information", "topic": "Fuses and Breakers", "question_text": "What is the purpose of a fuse in an electrical circuit?", "options": ["To increase voltage to components", "To protect the circuit by breaking when excessive current flows", "To reduce resistance", "To store energy during power outages"], "correct_index": 1, "difficulty": 1, "explanation": "A fuse contains a thin wire that melts when excessive current flows, breaking the circuit and preventing damage to wiring or components. Unlike a circuit breaker, a blown fuse must be replaced, not just reset.", "test_types": ["ASVAB"]},
    {"id": "EI044", "section": "Electronics Information", "topic": "Fuses and Breakers", "question_text": "A circuit breaker differs from a fuse because a circuit breaker:", "options": ["Carries higher current", "Can be reset after tripping", "Provides better protection", "Works on DC only"], "correct_index": 1, "difficulty": 1, "explanation": "Circuit breakers trip (open the circuit) when excessive current flows, but they can be manually reset after the overload is corrected. Fuses must be replaced after they blow. Both protect against overcurrent.", "test_types": ["ASVAB"]},

    # === VOLTAGE DIVIDER ===
    {"id": "EI045", "section": "Electronics Information", "topic": "Voltage Divider", "question_text": "In a voltage divider with R1=10Ω and R2=10Ω across a 20V supply, the voltage across R2 is:", "options": ["20V", "5V", "10V", "15V"], "correct_index": 2, "difficulty": 2, "explanation": "Voltage divider: Vout = Vin × R2/(R1+R2) = 20 × 10/(10+10) = 20 × 0.5 = 10V. Equal resistors split voltage equally. This formula calculates partial voltage drops.", "test_types": ["ASVAB"]},

    # === SHORT CIRCUITS ===
    {"id": "EI046", "section": "Electronics Information", "topic": "Short Circuits", "question_text": "A short circuit is dangerous because it:", "options": ["Increases resistance to maximum", "Creates a very low resistance path causing excessive current and heat", "Stops all current flow", "Reverses current direction"], "correct_index": 1, "difficulty": 1, "explanation": "A short circuit creates a very low resistance path (bypassing the load), causing massive current flow (I = V/R, R≈0 means I→∞). This generates extreme heat, potentially causing fires. Fuses and breakers protect against shorts.", "test_types": ["ASVAB"]},

    # === ADDITIONAL MIXED ELECTRONICS ===
    {"id": "EI047", "section": "Electronics Information", "topic": "Basic Concepts", "question_text": "What is the unit of electrical resistance?", "options": ["Volt", "Amp", "Ohm", "Watt"], "correct_index": 2, "difficulty": 1, "explanation": "Resistance is measured in ohms (Ω), named after Georg Ohm. Volts measure voltage (electrical pressure). Amps measure current (flow rate). Watts measure power.", "test_types": ["ASVAB"]},
    {"id": "EI048", "section": "Electronics Information", "topic": "Basic Concepts", "question_text": "What is the unit of electrical current?", "options": ["Ohm", "Volt", "Ampere", "Watt"], "correct_index": 2, "difficulty": 1, "explanation": "Current is measured in amperes (amps, A), named after André-Marie Ampère. It measures the rate of electron flow — how many charges pass a point per second.", "test_types": ["ASVAB"]},
    {"id": "EI049", "section": "Electronics Information", "topic": "Basic Concepts", "question_text": "Voltage is best described as:", "options": ["The number of electrons flowing per second", "The electrical pressure or potential difference that drives current", "The resistance of a conductor", "The power consumed by a device"], "correct_index": 1, "difficulty": 2, "explanation": "Voltage (measured in volts) is the electrical potential difference between two points — the 'pressure' that pushes electrons through a circuit. Without voltage, current cannot flow.", "test_types": ["ASVAB"]},
    {"id": "EI050", "section": "Electronics Information", "topic": "Series vs Parallel", "question_text": "Which type of circuit is most similar to a water pipe that can be turned off at one point to stop all flow?", "options": ["Parallel circuit", "Series circuit", "Short circuit", "Open circuit"], "correct_index": 1, "difficulty": 2, "explanation": "A series circuit has one single path — like one pipe. One break (open switch) stops all flow. A parallel circuit has multiple paths — like pipes with branches, so blocking one doesn't stop others.", "test_types": ["ASVAB"]},
    {"id": "EI051", "section": "Electronics Information", "topic": "Capacitors", "question_text": "Capacitors in series have a total capacitance that is:", "options": ["Greater than any single capacitor", "Equal to the sum of all capacitors", "Less than the smallest capacitor", "Unchanged from the first capacitor"], "correct_index": 2, "difficulty": 3, "explanation": "Capacitors in series use the reciprocal formula (like resistors in parallel): 1/C_total = 1/C1 + 1/C2 + ... The result is always less than the smallest capacitor. This is opposite to how resistors in series work.", "test_types": ["ASVAB"]},
    {"id": "EI052", "section": "Electronics Information", "topic": "Diodes", "question_text": "Which type of diode emits light when forward biased?", "options": ["Zener diode", "Rectifier diode", "LED (light-emitting diode)", "Photodiode"], "correct_index": 2, "difficulty": 1, "explanation": "An LED (Light-Emitting Diode) emits light when forward biased. Zener diodes are used for voltage regulation. Photodiodes generate current when exposed to light (the reverse of an LED).", "test_types": ["ASVAB"]},
    {"id": "EI053", "section": "Electronics Information", "topic": "Power", "question_text": "A device rated at 60W operating at 120V draws how much current?", "options": ["0.5A", "2A", "7,200A", "60A"], "correct_index": 0, "difficulty": 2, "explanation": "I = P/V = 60W / 120V = 0.5A. A standard light bulb drawing only half an amp explains why many appliances can share a household circuit (which typically handles 15-20A).", "test_types": ["ASVAB"]},
    {"id": "EI054", "section": "Electronics Information", "topic": "Ohm's Law", "question_text": "What happens to current in a circuit if resistance is increased while voltage stays constant?", "options": ["Current increases", "Current stays the same", "Current decreases", "Current reverses direction"], "correct_index": 2, "difficulty": 1, "explanation": "From Ohm's Law, I = V/R. If R increases and V is constant, I decreases. Resistance and current are inversely proportional (when voltage is constant).", "test_types": ["ASVAB"]},
    {"id": "EI055", "section": "Electronics Information", "topic": "Transformers", "question_text": "Why is electrical power transmitted at high voltage over long distances?", "options": ["High voltage charges batteries faster", "High voltage reduces current, which reduces power loss in wires (P=I²R)", "High voltage increases wire conductivity", "Transformers only work with high voltage"], "correct_index": 1, "difficulty": 3, "explanation": "Power loss in transmission lines is P_loss = I²R. Transmitting at high voltage reduces current (P = VI, same power but higher V means lower I), dramatically reducing I²R losses. Step-up transformers raise voltage for transmission; step-down transformers reduce it for homes.", "test_types": ["ASVAB"]},
    {"id": "EI056", "section": "Electronics Information", "topic": "Transistors", "question_text": "In digital electronics, a transistor acting as a switch is either:", "options": ["Partially on or partially off", "Fully on (saturated) or fully off (cut off)", "Slowly transitioning between states", "Responding only to AC signals"], "correct_index": 1, "difficulty": 2, "explanation": "Digital transistors are binary — fully on (saturated, maximum current, low voltage = logic 0 at output) or fully off (cut off, no current, high voltage = logic 1). Billions of these switches form modern processors.", "test_types": ["ASVAB"]},
    {"id": "EI057", "section": "Electronics Information", "topic": "Basic Concepts", "question_text": "Grounding a circuit provides:", "options": ["Additional power to the circuit", "A safe path for excess current to flow to Earth", "A resistance reference point", "Higher current capacity"], "correct_index": 1, "difficulty": 2, "explanation": "Grounding provides a safe return path for fault currents (like if a hot wire touches a metal case). The ground wire directs fault current to Earth, tripping the breaker/fuse rather than shocking a person who touches the device.", "test_types": ["ASVAB"]},
    {"id": "EI058", "section": "Electronics Information", "topic": "AC vs DC", "question_text": "Most consumer electronics (phones, computers) internally operate on:", "options": ["High-voltage AC", "Low-voltage DC", "High-frequency AC", "Variable DC"], "correct_index": 1, "difficulty": 2, "explanation": "Internal electronics (processors, memory, sensors) require low-voltage DC (typically 3.3V, 5V, or 12V). Power adapters/chargers convert household AC to low-voltage DC for devices.", "test_types": ["ASVAB"]},
    {"id": "EI059", "section": "Electronics Information", "topic": "Capacitors", "question_text": "One common use of capacitors in power supply circuits is to:", "options": ["Increase voltage", "Reduce resistance", "Smooth out voltage fluctuations (filter ripple)", "Convert DC to AC"], "correct_index": 2, "difficulty": 2, "explanation": "After a rectifier converts AC to pulsating DC, capacitors smooth the voltage by charging during peaks and discharging during troughs. This 'filter' produces steady DC. This is in every phone charger.", "test_types": ["ASVAB"]},
    {"id": "EI060", "section": "Electronics Information", "topic": "Inductors", "question_text": "An inductor's opposition to AC current is called:", "options": ["Resistance", "Capacitance", "Inductive reactance", "Impedance"], "correct_index": 2, "difficulty": 3, "explanation": "An inductor opposes changes in current. Its opposition to AC is called inductive reactance (XL = 2πfL, measured in ohms). Unlike resistance, reactance varies with frequency. Total AC opposition is impedance (Z).", "test_types": ["ASVAB"]},
    {"id": "EI061", "section": "Electronics Information", "topic": "Fuses and Breakers", "question_text": "If you replace a 15-amp fuse with a 30-amp fuse, the risk is:", "options": ["The circuit will run more efficiently", "The fuse will blow immediately", "Wiring can overheat and catch fire before the fuse blows", "Voltage in the circuit will increase"], "correct_index": 2, "difficulty": 2, "explanation": "Fuses must match the wire rating. A 30A fuse in a 15A-rated circuit allows twice the safe current to flow — the wiring can overheat and start a fire before the oversized fuse blows. Always match fuse size to wire rating.", "test_types": ["ASVAB"]},
    {"id": "EI062", "section": "Electronics Information", "topic": "Basic Concepts", "question_text": "A multimeter can measure all of the following EXCEPT:", "options": ["Voltage", "Current", "Resistance", "Inductance (directly)"], "correct_index": 3, "difficulty": 2, "explanation": "A standard multimeter measures voltage (V), current (A), and resistance (Ω). Measuring inductance directly requires a specialized LCR meter. Some advanced multimeters include capacitance measurement.", "test_types": ["ASVAB"]},
    {"id": "EI063", "section": "Electronics Information", "topic": "Series Circuits", "question_text": "In a series circuit with a 9V battery and three identical resistors, the voltage across each resistor is:", "options": ["9V", "3V", "27V", "1V"], "correct_index": 1, "difficulty": 1, "explanation": "In series, voltage divides equally among identical resistors. 9V ÷ 3 = 3V per resistor. The total voltage always equals the sum of individual voltage drops (Kirchhoff's Voltage Law).", "test_types": ["ASVAB"]},
    {"id": "EI064", "section": "Electronics Information", "topic": "Parallel Circuits", "question_text": "In a parallel circuit, if one branch is disconnected, the other branches:", "options": ["Also stop working", "Draw more current to compensate", "Continue working normally", "Have reduced voltage"], "correct_index": 2, "difficulty": 1, "explanation": "In parallel, each branch is independent. Disconnecting one branch does not affect others — they still receive full voltage. This is why household circuits are parallel: one device failing doesn't affect others.", "test_types": ["ASVAB"]},
    {"id": "EI065", "section": "Electronics Information", "topic": "Diodes", "question_text": "A Zener diode is commonly used for:", "options": ["Light emission", "Voltage regulation (maintaining a fixed voltage)", "Amplification", "Rectification only"], "correct_index": 1, "difficulty": 3, "explanation": "Zener diodes are designed to operate in reverse breakdown at a specific voltage (the Zener voltage). This makes them ideal for voltage regulation — they clamp voltage to a fixed value in a circuit.", "test_types": ["ASVAB"]},
    {"id": "EI066", "section": "Electronics Information", "topic": "Basic Concepts", "question_text": "Kirchhoff's Current Law states that:", "options": ["Voltage is the same at all points", "The sum of currents entering a junction equals the sum leaving it", "Resistance increases with temperature", "Power is conserved in a transformer"], "correct_index": 1, "difficulty": 3, "explanation": "Kirchhoff's Current Law (KCL): the total current entering any junction must equal the total current leaving it. This is a form of conservation of charge. It's used to analyze complex circuit junctions.", "test_types": ["ASVAB"]},
    {"id": "EI067", "section": "Electronics Information", "topic": "Basic Concepts", "question_text": "The function of a resistor in a circuit is to:", "options": ["Store electrical charge", "Oppose current flow and drop voltage", "Amplify the signal", "Convert AC to DC"], "correct_index": 1, "difficulty": 1, "explanation": "Resistors oppose current flow (consume/dissipate energy as heat) and create voltage drops. They are used to limit current, divide voltage, and set operating points for transistors.", "test_types": ["ASVAB"]},
    {"id": "EI068", "section": "Electronics Information", "topic": "AC vs DC", "question_text": "In an AC circuit, the voltage measured by a voltmeter reads:", "options": ["Peak voltage", "Average voltage (which is zero)", "RMS (root mean square) voltage", "Instantaneous voltage"], "correct_index": 2, "difficulty": 3, "explanation": "AC voltmeters read RMS (root mean square) voltage — the effective DC equivalent. US household 120V AC means 120V RMS; the actual peak voltage is about 170V. RMS is what matters for power calculations.", "test_types": ["ASVAB"]},
    {"id": "EI069", "section": "Electronics Information", "topic": "Transformers", "question_text": "A transformer with 500 primary turns and 50 secondary turns is a:", "options": ["Step-up transformer", "Step-down transformer", "Isolation transformer", "Frequency transformer"], "correct_index": 1, "difficulty": 2, "explanation": "More primary turns than secondary = step-down transformer (reduces voltage). The turns ratio is 10:1, so output voltage is 1/10 of input voltage. Step-up has more secondary turns than primary.", "test_types": ["ASVAB"]},
    {"id": "EI070", "section": "Electronics Information", "topic": "Power", "question_text": "Energy consumed by an appliance is measured in:", "options": ["Watts", "Amperes", "Kilowatt-hours", "Volts"], "correct_index": 2, "difficulty": 2, "explanation": "Energy = Power × Time. Kilowatt-hours (kWh) are used for billing energy consumption. Watts measure the rate of power use. A 1,000W (1 kW) appliance running for 1 hour uses 1 kWh of energy.", "test_types": ["ASVAB"]},
    {"id": "EI071", "section": "Electronics Information", "topic": "Conductors and Insulators", "question_text": "Why is copper used for electrical wiring instead of silver (a better conductor)?", "options": ["Copper has lower resistance than silver", "Copper is much less expensive while still being highly conductive", "Silver oxidizes too quickly", "Copper handles higher voltages"], "correct_index": 1, "difficulty": 2, "explanation": "Silver has slightly lower resistance but is far too expensive for widespread use. Copper offers an excellent balance of conductivity and cost, making it the standard for electrical wiring.", "test_types": ["ASVAB"]},
    {"id": "EI072", "section": "Electronics Information", "topic": "Capacitors", "question_text": "Which component would you use to block DC while allowing AC to pass?", "options": ["Resistor", "Inductor", "Capacitor", "Transformer"], "correct_index": 2, "difficulty": 2, "explanation": "A capacitor blocks DC (charges up and then no more current flows) but passes AC (the alternating voltage constantly charges/discharges it). This is called a coupling or blocking capacitor and is used in audio amplifiers.", "test_types": ["ASVAB"]},
    {"id": "EI073", "section": "Electronics Information", "topic": "Inductors", "question_text": "An inductor opposes high-frequency AC more than low-frequency AC because:", "options": ["Higher frequency means more voltage", "Inductive reactance (XL) increases with frequency (XL = 2πfL)", "Low frequency causes magnetic saturation", "High frequency heats the coil more"], "correct_index": 1, "difficulty": 3, "explanation": "Inductive reactance XL = 2πfL. As frequency (f) increases, XL increases. This means inductors block high frequencies more than low frequencies — the opposite of capacitors. This property is used in LC filters.", "test_types": ["ASVAB"]},
    {"id": "EI074", "section": "Electronics Information", "topic": "Basic Concepts", "question_text": "What does the abbreviation 'EMF' stand for in electronics?", "options": ["Electrical Measurement Force", "Electromagnetic Field", "Electromotive Force", "Electronic Modulation Factor"], "correct_index": 2, "difficulty": 2, "explanation": "EMF stands for Electromotive Force — the voltage generated by a source (battery, generator) that drives current through a circuit. Despite having 'force' in the name, EMF is measured in volts, not newtons.", "test_types": ["ASVAB"]},
    {"id": "EI075", "section": "Electronics Information", "topic": "Series vs Parallel", "question_text": "An ohmmeter measures resistance. To measure a resistor correctly, the resistor must be:", "options": ["Connected to the circuit while powered", "Removed from the circuit (disconnected)", "Connected in series with the power supply", "Measured while current is flowing"], "correct_index": 1, "difficulty": 2, "explanation": "To accurately measure resistance, the component must be disconnected from the circuit. If measured in-circuit, parallel paths and powered components give false readings. Always de-energize and isolate the component.", "test_types": ["ASVAB"]},
]

if __name__ == "__main__":
    print(f"EI question count: {len(EI_QUESTIONS)}")
