#!/usr/bin/env python3
"""Auto & Shop Information questions — 75 questions"""

AS_QUESTIONS = [
    # === 4-STROKE ENGINE CYCLE ===
    {"id": "AS001", "section": "Auto and Shop Information", "topic": "Engine Cycles", "question_text": "In what order do the four strokes of a gasoline engine occur?", "options": ["Compression, Intake, Power, Exhaust", "Intake, Compression, Power, Exhaust", "Power, Intake, Compression, Exhaust", "Intake, Power, Compression, Exhaust"], "correct_index": 1, "difficulty": 1, "explanation": "The four strokes in order: (1) Intake — piston moves down, drawing in air-fuel mixture; (2) Compression — piston moves up, compressing mixture; (3) Power — spark ignites mixture, piston forced down; (4) Exhaust — piston moves up, pushing out burned gases.", "test_types": ["ASVAB"]},
    {"id": "AS002", "section": "Auto and Shop Information", "topic": "Engine Cycles", "question_text": "During which stroke of a 4-stroke engine does combustion (burning of fuel) occur?", "options": ["Intake stroke", "Compression stroke", "Power stroke", "Exhaust stroke"], "correct_index": 2, "difficulty": 1, "explanation": "The power stroke: the compressed air-fuel mixture is ignited by the spark plug, causing rapid expansion that drives the piston down, converting chemical energy to mechanical motion.", "test_types": ["ASVAB"]},
    {"id": "AS003", "section": "Auto and Shop Information", "topic": "Engine Cycles", "question_text": "During the compression stroke, what does the piston do?", "options": ["Moves down, drawing in fuel mixture", "Moves up, compressing the air-fuel mixture", "Moves down as combustion occurs", "Moves up, pushing out exhaust gases"], "correct_index": 1, "difficulty": 1, "explanation": "During the compression stroke, both intake and exhaust valves are closed, and the piston moves up, compressing the air-fuel mixture. Compression increases temperature and makes combustion more efficient and powerful.", "test_types": ["ASVAB"]},
    {"id": "AS004", "section": "Auto and Shop Information", "topic": "Engine Cycles", "question_text": "A diesel engine differs from a gasoline engine in that a diesel engine:", "options": ["Uses spark plugs to ignite fuel", "Has only two strokes", "Ignites fuel by compression alone (no spark plugs)", "Runs cooler than gasoline engines"], "correct_index": 2, "difficulty": 2, "explanation": "Diesel engines use very high compression ratios (around 20:1 vs. 10:1 for gasoline) to heat the air so much that diesel fuel ignites spontaneously. No spark plugs are needed.", "test_types": ["ASVAB"]},

    # === ENGINE COMPONENTS ===
    {"id": "AS005", "section": "Auto and Shop Information", "topic": "Engine Components", "question_text": "What is the function of the crankshaft?", "options": ["Opens and closes the valves", "Converts the up-down motion of pistons into rotational motion", "Pumps oil throughout the engine", "Controls ignition timing"], "correct_index": 1, "difficulty": 1, "explanation": "The crankshaft converts the reciprocating (up-down) motion of the pistons into rotational motion that drives the transmission and wheels. It is one of the most critical engine components.", "test_types": ["ASVAB"]},
    {"id": "AS006", "section": "Auto and Shop Information", "topic": "Engine Components", "question_text": "The camshaft controls:", "options": ["Engine speed", "Opening and closing of intake and exhaust valves", "Fuel injection timing only", "Crankshaft rotation speed"], "correct_index": 1, "difficulty": 1, "explanation": "The camshaft's lobes (cams) push on the valve train to open and close the intake and exhaust valves at precisely the right times in the engine cycle. It is driven by the crankshaft via a timing chain or belt.", "test_types": ["ASVAB"]},
    {"id": "AS007", "section": "Auto and Shop Information", "topic": "Engine Components", "question_text": "What is the purpose of the head gasket?", "options": ["To lubricate the pistons", "To seal the joint between the engine block and cylinder head", "To control coolant temperature", "To connect the crankshaft to the camshaft"], "correct_index": 1, "difficulty": 2, "explanation": "The head gasket seals the mating surface between the engine block and cylinder head. It must seal combustion pressure, coolant passages, and oil passages. A blown head gasket allows coolant and/or oil to leak into combustion chambers.", "test_types": ["ASVAB"]},
    {"id": "AS008", "section": "Auto and Shop Information", "topic": "Engine Components", "question_text": "The spark plug's purpose is to:", "options": ["Regulate fuel flow", "Create a spark to ignite the compressed air-fuel mixture", "Measure engine temperature", "Release exhaust gases"], "correct_index": 1, "difficulty": 1, "explanation": "The spark plug fires an electrical spark at precisely the right moment to ignite the compressed air-fuel mixture during the power stroke. It screws into the cylinder head above each combustion chamber.", "test_types": ["ASVAB"]},
    {"id": "AS009", "section": "Auto and Shop Information", "topic": "Engine Components", "question_text": "Pistons move inside:", "options": ["The crankcase", "The cylinders", "The exhaust manifold", "The intake manifold"], "correct_index": 1, "difficulty": 1, "explanation": "Pistons move up and down inside the cylinders (cylindrical bores in the engine block). Piston rings on the piston seal against the cylinder walls to contain combustion pressure and control oil.", "test_types": ["ASVAB"]},

    # === COOLING SYSTEM ===
    {"id": "AS010", "section": "Auto and Shop Information", "topic": "Cooling System", "question_text": "What is the primary purpose of the radiator?", "options": ["Store coolant for the engine", "Cool the hot coolant by passing it through air-cooled fins", "Pressurize the cooling system", "Mix coolant with oil for lubrication"], "correct_index": 1, "difficulty": 1, "explanation": "The radiator is a heat exchanger — hot coolant from the engine flows through its fins, and air passing over the fins (from driving or the cooling fan) removes heat before the coolant returns to the engine.", "test_types": ["ASVAB"]},
    {"id": "AS011", "section": "Auto and Shop Information", "topic": "Cooling System", "question_text": "What does the thermostat regulate in an engine's cooling system?", "options": ["The amount of coolant in the system", "The coolant flow to maintain optimal engine operating temperature", "The radiator fan speed", "The pressure in the cooling system"], "correct_index": 1, "difficulty": 2, "explanation": "The thermostat is a temperature-controlled valve. It stays closed when the engine is cold (keeping coolant in the engine to warm up faster) and opens when the engine reaches operating temperature (allowing coolant to flow to the radiator for cooling).", "test_types": ["ASVAB"]},
    {"id": "AS012", "section": "Auto and Shop Information", "topic": "Cooling System", "question_text": "Antifreeze (coolant) does all of the following EXCEPT:", "options": ["Lower the freezing point of coolant", "Raise the boiling point of coolant", "Prevent corrosion in the cooling system", "Lubricate the pistons"], "correct_index": 3, "difficulty": 2, "explanation": "Antifreeze (ethylene glycol + water) prevents freezing in winter, raises the boiling point to prevent overheating, and contains corrosion inhibitors. Engine oil lubricates pistons, not coolant.", "test_types": ["ASVAB"]},
    {"id": "AS013", "section": "Auto and Shop Information", "topic": "Cooling System", "question_text": "The water pump in a cooling system:", "options": ["Stores excess coolant", "Circulates coolant through the engine and radiator", "Regulates coolant temperature", "Removes air bubbles from the system"], "correct_index": 1, "difficulty": 1, "explanation": "The water pump is driven by the engine (via belt or chain) and continuously circulates coolant through the engine block, cylinder head, and radiator. A failing water pump causes overheating.", "test_types": ["ASVAB"]},

    # === LUBRICATION SYSTEM ===
    {"id": "AS014", "section": "Auto and Shop Information", "topic": "Lubrication", "question_text": "Engine oil serves which of the following functions?", "options": ["Only lubrication of moving parts", "Lubrication, cooling, cleaning, and sealing", "Only cooling of the engine", "Only sealing piston rings"], "correct_index": 1, "difficulty": 2, "explanation": "Engine oil lubricates moving parts (reduces friction), cools components that coolant can't reach, cleans by carrying debris to the oil filter, and helps seal between piston rings and cylinder walls.", "test_types": ["ASVAB"]},
    {"id": "AS015", "section": "Auto and Shop Information", "topic": "Lubrication", "question_text": "Low engine oil pressure is dangerous because:", "options": ["It increases fuel consumption", "It causes the engine to overheat through the cooling system", "Moving parts are not adequately lubricated, causing rapid wear and damage", "The battery loses charge faster"], "correct_index": 2, "difficulty": 2, "explanation": "Low oil pressure means oil is not being forced to lubrication points fast enough. Metal surfaces contact metal directly, causing extreme wear, heat, and potentially catastrophic engine failure (seized engine).", "test_types": ["ASVAB"]},
    {"id": "AS016", "section": "Auto and Shop Information", "topic": "Lubrication", "question_text": "What is the function of the oil filter?", "options": ["Cool the engine oil", "Remove contaminants (dirt, metal particles) from the oil", "Measure oil pressure", "Regulate the amount of oil used"], "correct_index": 1, "difficulty": 1, "explanation": "The oil filter removes contaminants — metal particles, dirt, carbon deposits — from the engine oil as it circulates. Filters are changed with oil changes to prevent buildup of harmful particles.", "test_types": ["ASVAB"]},

    # === FUEL SYSTEM ===
    {"id": "AS017", "section": "Auto and Shop Information", "topic": "Fuel System", "question_text": "A fuel injector's job is to:", "options": ["Store fuel near the engine", "Spray a precisely measured amount of fuel into the intake manifold or cylinder", "Filter contaminants from the fuel", "Mix fuel with engine oil"], "correct_index": 1, "difficulty": 1, "explanation": "Fuel injectors spray atomized (fine mist) fuel at precise amounts and timing, controlled by the engine computer (ECU). This replaced carburetors because it provides better fuel economy and lower emissions.", "test_types": ["ASVAB"]},
    {"id": "AS018", "section": "Auto and Shop Information", "topic": "Fuel System", "question_text": "How does fuel injection differ from a carburetor?", "options": ["Fuel injection uses more fuel", "Fuel injection uses computer control for precise fuel delivery; carburetors use air flow venturi effect", "Carburetors are found only in diesel engines", "Fuel injection works only at high speeds"], "correct_index": 1, "difficulty": 2, "explanation": "Carburetors use the venturi effect (air flow creating suction) to draw fuel from a bowl — mechanical and simple but imprecise. Fuel injection uses electronic sensors and an ECU to deliver exactly the right fuel amount.", "test_types": ["ASVAB"]},
    {"id": "AS019", "section": "Auto and Shop Information", "topic": "Fuel System", "question_text": "The fuel filter prevents:", "options": ["Fuel from evaporating", "Contamination (dirt, rust particles) from reaching the injectors or carburetor", "The fuel pump from over-pressurizing", "Fuel from mixing with oil"], "correct_index": 1, "difficulty": 1, "explanation": "The fuel filter catches contaminants before they reach the fuel injectors or carburetor. Clogged injectors cause poor performance. Fuel filters should be replaced periodically.", "test_types": ["ASVAB"]},

    # === IGNITION SYSTEM ===
    {"id": "AS020", "section": "Auto and Shop Information", "topic": "Ignition System", "question_text": "The alternator in a car:", "options": ["Starts the engine", "Generates electricity to charge the battery and power electronics while running", "Controls ignition timing", "Regulates fuel pressure"], "correct_index": 1, "difficulty": 1, "explanation": "The alternator is an AC generator driven by the engine belt. It generates electricity to power the car's electrical systems while running and recharges the battery. Without it, the battery drains completely.", "test_types": ["ASVAB"]},
    {"id": "AS021", "section": "Auto and Shop Information", "topic": "Ignition System", "question_text": "The starter motor's purpose is to:", "options": ["Keep the engine running after starting", "Crank the engine to begin the combustion cycle", "Generate electricity for the battery", "Control ignition timing"], "correct_index": 1, "difficulty": 1, "explanation": "The starter motor is an electric motor powered by the battery. It cranks (turns) the engine fast enough to start the combustion cycle. Once the engine runs, the starter disengages.", "test_types": ["ASVAB"]},
    {"id": "AS022", "section": "Auto and Shop Information", "topic": "Ignition System", "question_text": "If a car battery is dead, the car will:", "options": ["Run but have dim lights", "Not start, as the starter motor needs battery power", "Start but immediately stall", "Have reduced engine power only"], "correct_index": 1, "difficulty": 1, "explanation": "A dead battery means no power to the starter motor, so the engine cannot crank. The engine needs battery power to start. Jump-starting provides external power to start the engine; the alternator then recharges the battery.", "test_types": ["ASVAB"]},
    {"id": "AS023", "section": "Auto and Shop Information", "topic": "Ignition System", "question_text": "In older vehicles, the distributor was used to:", "options": ["Distribute fuel to each cylinder", "Route high-voltage ignition pulses to each spark plug in the correct sequence", "Control the cooling fan", "Regulate battery charging"], "correct_index": 1, "difficulty": 2, "explanation": "The distributor routed the high-voltage spark from the ignition coil to each spark plug in the correct firing order. Modern vehicles use distributorless ignition systems (DIS) or coil-on-plug designs instead.", "test_types": ["ASVAB"]},

    # === TRANSMISSION ===
    {"id": "AS024", "section": "Auto and Shop Information", "topic": "Transmission", "question_text": "The purpose of the transmission is to:", "options": ["Convert exhaust gases to power", "Transfer and change the engine's rotational speed and torque to the drive wheels", "Control fuel flow to the engine", "Regulate engine cooling"], "correct_index": 1, "difficulty": 1, "explanation": "The transmission transfers power from the engine to the drive wheels while allowing the driver to select different gear ratios. Lower gears provide more torque (for acceleration/hills); higher gears allow higher speed.", "test_types": ["ASVAB"]},
    {"id": "AS025", "section": "Auto and Shop Information", "topic": "Transmission", "question_text": "In a manual transmission, the clutch is used to:", "options": ["Select which gear to use", "Temporarily disconnect the engine from the transmission to allow gear changes", "Engage the parking brake", "Control the throttle"], "correct_index": 1, "difficulty": 1, "explanation": "The clutch is a friction disc that connects/disconnects the engine from the transmission. Pressing the clutch pedal disengages the engine, allowing gear shifts without grinding. Releasing it re-engages engine power.", "test_types": ["ASVAB"]},
    {"id": "AS026", "section": "Auto and Shop Information", "topic": "Transmission", "question_text": "An automatic transmission uses what device instead of a manual clutch?", "options": ["A flywheel", "A torque converter", "A differential", "A CV joint"], "correct_index": 1, "difficulty": 2, "explanation": "An automatic transmission uses a torque converter (a fluid coupling) instead of a manual clutch. It uses hydraulic fluid to transfer torque smoothly from the engine to the transmission, allowing automatic gear changes.", "test_types": ["ASVAB"]},
    {"id": "AS027", "section": "Auto and Shop Information", "topic": "Transmission", "question_text": "A lower gear ratio provides:", "options": ["Higher top speed", "More torque and pulling power at lower speeds", "Better fuel economy at highway speeds", "Less engine strain at all speeds"], "correct_index": 1, "difficulty": 2, "explanation": "Lower gears multiply torque — the engine turns more times per wheel rotation, providing more force (torque) to the wheels. This is why you downshift for hills, towing, or starting from a stop.", "test_types": ["ASVAB"]},

    # === BRAKES ===
    {"id": "AS028", "section": "Auto and Shop Information", "topic": "Brakes", "question_text": "Disc brakes work by:", "options": ["Expanding brake shoes inside a drum", "Hydraulic calipers squeezing brake pads against a spinning rotor", "A cable pulling brake pads together", "Electromagnetic resistance in the wheel"], "correct_index": 1, "difficulty": 1, "explanation": "Disc brakes: hydraulic pressure moves a caliper, which squeezes brake pads against both sides of a spinning rotor (disc). Friction slows the rotor and wheel. Disc brakes dissipate heat better than drum brakes.", "test_types": ["ASVAB"]},
    {"id": "AS029", "section": "Auto and Shop Information", "topic": "Brakes", "question_text": "Drum brakes work by:", "options": ["Squeezing pads against a disc", "Expanding curved brake shoes outward against the inside of a drum", "Applying magnetic force to the wheel", "Using a cable to grip the wheel directly"], "correct_index": 1, "difficulty": 2, "explanation": "Drum brakes use wheel cylinders to push curved brake shoes outward against the inside surface of a spinning drum. They are less effective for heat dissipation than disc brakes and are often used on rear wheels.", "test_types": ["ASVAB"]},
    {"id": "AS030", "section": "Auto and Shop Information", "topic": "Brakes", "question_text": "ABS (Anti-lock Braking System) prevents:", "options": ["Brake fluid from overheating", "The wheels from locking up during hard braking, maintaining steering control", "The brakes from wearing too quickly", "Brake fade on long downhill grades"], "correct_index": 1, "difficulty": 1, "explanation": "ABS rapidly pulses braking force to prevent wheel lock-up during hard stops. Locked wheels cause skidding and loss of steering. ABS allows the driver to steer while braking hard.", "test_types": ["ASVAB"]},
    {"id": "AS031", "section": "Auto and Shop Information", "topic": "Brakes", "question_text": "Brake fluid is important because:", "options": ["It lubricates brake pads", "It is the hydraulic fluid that transmits pedal force to the brake calipers/wheel cylinders", "It cools the brake rotors", "It prevents brake fade"], "correct_index": 1, "difficulty": 2, "explanation": "Brake fluid is hydraulic fluid — pressing the brake pedal creates pressure in the fluid, which is transmitted through the brake lines to the calipers or wheel cylinders. Brake fluid is hygroscopic (absorbs water), lowering its boiling point over time.", "test_types": ["ASVAB"]},
    {"id": "AS032", "section": "Auto and Shop Information", "topic": "Brakes", "question_text": "The master cylinder in the brake system:", "options": ["Adjusts brake pad clearance", "Converts pedal pressure into hydraulic pressure in the brake lines", "Stores brake fluid reserves", "Controls ABS pulsing"], "correct_index": 1, "difficulty": 2, "explanation": "The master cylinder is connected to the brake pedal. When pressed, it pressurizes the brake fluid in the hydraulic lines. The reservoir on top holds extra fluid. A leak in the master cylinder means soft or no brakes.", "test_types": ["ASVAB"]},

    # === ELECTRICAL SYSTEM ===
    {"id": "AS033", "section": "Auto and Shop Information", "topic": "Electrical System", "question_text": "A car's standard electrical system operates at approximately:", "options": ["6 volts DC", "12 volts DC", "24 volts AC", "120 volts AC"], "correct_index": 1, "difficulty": 1, "explanation": "Standard passenger vehicles use a 12-volt DC electrical system. Heavy trucks and equipment often use 24V systems. The 12V comes from the battery; the alternator maintains the charge.", "test_types": ["ASVAB"]},
    {"id": "AS034", "section": "Auto and Shop Information", "topic": "Electrical System", "question_text": "In a car's electrical system, the ground (negative) terminal is typically connected to:", "options": ["The fuel tank", "The engine block and body of the vehicle", "The battery positive terminal", "The fuse box only"], "correct_index": 1, "difficulty": 2, "explanation": "In an automotive electrical system, the vehicle's body, frame, and engine block serve as the ground (negative) return path. This is called a 'chassis ground' and completes the circuit for all electrical components.", "test_types": ["ASVAB"]},
    {"id": "AS035", "section": "Auto and Shop Information", "topic": "Electrical System", "question_text": "Automotive fuses protect electrical circuits from:", "options": ["Voltage spikes from the alternator", "Excessive current that could damage wiring or components", "Short circuits only", "Battery discharge when parked"], "correct_index": 1, "difficulty": 1, "explanation": "Automotive fuses are designed to blow (melt) when excessive current flows, protecting the wiring and components. Each circuit has a fuse rated for the maximum safe current of that circuit.", "test_types": ["ASVAB"]},

    # === TIRES ===
    {"id": "AS036", "section": "Auto and Shop Information", "topic": "Tires", "question_text": "Correct tire inflation is important because under-inflation causes:", "options": ["The center of the tread to wear faster", "Excessive heat buildup and possible tire failure", "Overinflation symptoms", "The vehicle to handle better"], "correct_index": 1, "difficulty": 2, "explanation": "Under-inflated tires flex excessively, building up heat that can cause blowouts. They also wear the outer edges faster, reduce fuel economy, and impair handling. Check tire pressure monthly.", "test_types": ["ASVAB"]},
    {"id": "AS037", "section": "Auto and Shop Information", "topic": "Tires", "question_text": "Tire rotation is performed to:", "options": ["Balance the tires", "Equalize tread wear among all four tires to extend tire life", "Check for alignment problems", "Improve fuel economy immediately"], "correct_index": 1, "difficulty": 1, "explanation": "Front and rear tires wear differently (front tires steer and often brake harder). Regular rotation (typically every 5,000-7,500 miles) moves tires to different positions so all four wear evenly, extending tire life.", "test_types": ["ASVAB"]},
    {"id": "AS038", "section": "Auto and Shop Information", "topic": "Tires", "question_text": "Wheel alignment refers to:", "options": ["The balance of weight distribution in a tire", "Adjusting the angles of the wheels so they are parallel to each other and perpendicular to the ground", "The pressure inside the tire", "The rotation pattern of tires"], "correct_index": 1, "difficulty": 2, "explanation": "Alignment adjusts camber, caster, and toe angles of the wheels. Misalignment causes uneven tire wear, pulling to one side, and poor handling. Wheel balancing (different from alignment) corrects uneven weight distribution in a tire/wheel assembly.", "test_types": ["ASVAB"]},
    {"id": "AS039", "section": "Auto and Shop Information", "topic": "Tires", "question_text": "Tire pressure is measured in:", "options": ["Newtons", "Ohms", "PSI (pounds per square inch)", "RPM"], "correct_index": 2, "difficulty": 1, "explanation": "Tire pressure is measured in PSI (pounds per square inch) in the US, or kPa (kilopascals) in metric countries. Typical passenger car tires are inflated to 30-35 PSI. The correct pressure is listed in the owner's manual or door jamb sticker.", "test_types": ["ASVAB"]},

    # === TOOLS ===
    {"id": "AS040", "section": "Auto and Shop Information", "topic": "Tools", "question_text": "A torque wrench is used to:", "options": ["Break loose very tight bolts", "Tighten fasteners to a specified torque value (foot-pounds or Newton-meters)", "Measure bolt diameter", "Remove stripped bolts"], "correct_index": 1, "difficulty": 1, "explanation": "A torque wrench tightens fasteners to an exact specification. Critical fasteners (cylinder head bolts, lug nuts, suspension components) have torque specs that ensure proper clamping force without over-tightening and breaking bolts.", "test_types": ["ASVAB"]},
    {"id": "AS041", "section": "Auto and Shop Information", "topic": "Tools", "question_text": "A micrometer is used to:", "options": ["Measure electrical resistance", "Measure very small dimensions (shaft diameters, bearing clearances) with high precision", "Check fluid levels", "Test ignition coil voltage"], "correct_index": 1, "difficulty": 2, "explanation": "A micrometer (outside micrometer) measures precise outside dimensions to within 0.001 inch or 0.01 mm. Used for engine work: measuring crankshaft journals, piston diameters, and ring gap.", "test_types": ["ASVAB"]},
    {"id": "AS042", "section": "Auto and Shop Information", "topic": "Tools", "question_text": "A feeler gauge is used to measure:", "options": ["Fluid levels in reservoirs", "Small gaps or clearances (such as spark plug gap or valve clearance)", "Electrical voltage in circuits", "Tire tread depth"], "correct_index": 1, "difficulty": 2, "explanation": "A feeler gauge is a set of thin metal blades of known thickness used to measure gaps. Common uses: spark plug gap, valve clearance, brake rotor thickness variation, and bearing clearances.", "test_types": ["ASVAB"]},
    {"id": "AS043", "section": "Auto and Shop Information", "topic": "Tools", "question_text": "Which wrench is best suited for tightening bolts in a confined space where a swing arc is limited?", "options": ["Open-end wrench", "Combination wrench", "Ratchet and socket", "Adjustable wrench"], "correct_index": 2, "difficulty": 2, "explanation": "A ratchet and socket allows tightening with a short back-and-forth motion — you don't need to reposition the wrench after each stroke. This is ideal in confined spaces. Open-end and adjustable wrenches require more swing arc.", "test_types": ["ASVAB"]},
    {"id": "AS044", "section": "Auto and Shop Information", "topic": "Tools", "question_text": "An Allen key (hex key) is used with:", "options": ["Square-head bolts", "Hexagonal (hex) socket head screws and bolts", "Phillips head screws", "Torx fasteners"], "correct_index": 1, "difficulty": 1, "explanation": "Allen keys (hex keys) fit into the hexagonal socket (hole) in socket-head cap screws and set screws. They are common in bicycles, furniture assembly, and machinery.", "test_types": ["ASVAB"]},
    {"id": "AS045", "section": "Auto and Shop Information", "topic": "Tools", "question_text": "A hacksaw is used to:", "options": ["Shape metal by filing", "Cut metal, plastic, or pipe", "Drive screws into metal", "Measure metal thickness"], "correct_index": 1, "difficulty": 1, "explanation": "A hacksaw cuts through metal, plastic, conduit, and pipe using a fine-toothed replaceable blade. The teeth point forward, cutting on the push stroke. Different blade tooth counts suit different materials.", "test_types": ["ASVAB"]},
    {"id": "AS046", "section": "Auto and Shop Information", "topic": "Tools", "question_text": "A C-clamp is used to:", "options": ["Cut metal in a curved line", "Hold workpieces firmly in place while cutting, welding, or gluing", "Measure the inside diameter of a cylinder", "Remove seized bolts"], "correct_index": 1, "difficulty": 1, "explanation": "A C-clamp holds materials together or secures them to a workbench. The C-shaped frame and threaded screw apply clamping force. Common in woodworking and metalworking.", "test_types": ["ASVAB"]},
    {"id": "AS047", "section": "Auto and Shop Information", "topic": "Tools", "question_text": "Vernier calipers (or digital calipers) are used to:", "options": ["Measure electrical continuity", "Precisely measure inside, outside, and depth dimensions", "Check bearing preload", "Measure torque on fasteners"], "correct_index": 1, "difficulty": 2, "explanation": "Calipers measure inside dimensions (bore), outside dimensions (shaft), step dimensions, and depth — typically to 0.001 inch or 0.02 mm. More versatile than a micrometer, though slightly less precise.", "test_types": ["ASVAB"]},
    {"id": "AS048", "section": "Auto and Shop Information", "topic": "Safety", "question_text": "Why should safety glasses always be worn in the shop?", "options": ["To improve vision in low light", "To protect eyes from flying debris, sparks, and chemical splashes", "To reduce eye strain from bright lights", "Required only when welding"], "correct_index": 1, "difficulty": 1, "explanation": "Safety glasses protect against flying metal chips (grinding, drilling), sparks (welding, grinding), chemical splashes (battery acid, solvents), and debris. Eye injuries can be permanent — eye protection is required even for minor tasks.", "test_types": ["ASVAB"]},

    # === ADDITIONAL AUTO SHOP TOPICS ===
    {"id": "AS049", "section": "Auto and Shop Information", "topic": "Engine Components", "question_text": "The timing belt (or timing chain) connects:", "options": ["The alternator to the engine", "The crankshaft to the camshaft to synchronize valve timing with piston movement", "The engine to the transmission", "The water pump to the radiator"], "correct_index": 1, "difficulty": 2, "explanation": "The timing belt/chain keeps the crankshaft and camshaft synchronized. If it breaks, valves open at the wrong time — in interference engines, pistons can hit open valves, causing catastrophic engine damage.", "test_types": ["ASVAB"]},
    {"id": "AS050", "section": "Auto and Shop Information", "topic": "Engine", "question_text": "What does engine displacement refer to?", "options": ["The weight of the engine", "The total volume swept by all pistons in one stroke cycle (measured in liters or cubic inches)", "The maximum RPM of the engine", "The number of camshafts in the engine"], "correct_index": 1, "difficulty": 2, "explanation": "Displacement is the total cylinder volume swept by all pistons. A 2.0L engine has 2 liters of total piston displacement. Generally, more displacement means more power potential and fuel consumption.", "test_types": ["ASVAB"]},
    {"id": "AS051", "section": "Auto and Shop Information", "topic": "Engine", "question_text": "An overhead cam (OHC) engine has the camshaft located:", "options": ["In the engine block, below the pistons", "In the cylinder head, above the valves", "Inside the oil pan", "On the outside of the engine block"], "correct_index": 1, "difficulty": 3, "explanation": "Overhead cam (OHC) engines place the camshaft(s) in the cylinder head, directly above the valves. This reduces valve train mass, allowing higher RPM and better breathing. DOHC (dual overhead cam) has separate cams for intake and exhaust valves.", "test_types": ["ASVAB"]},
    {"id": "AS052", "section": "Auto and Shop Information", "topic": "Cooling System", "question_text": "If the temperature gauge rises to the red zone while driving, you should:", "options": ["Turn on the air conditioner to cool the engine", "Continue driving to reach a service station quickly", "Pull over safely and turn off the engine to prevent damage", "Turn the heater on full blast to help cool the engine"], "correct_index": 2, "difficulty": 1, "explanation": "Pull over and stop the engine. Driving an overheating engine causes warped heads, blown head gaskets, or seized pistons. Turning on the heater actually does help extract some heat but stopping is safer.", "test_types": ["ASVAB"]},
    {"id": "AS053", "section": "Auto and Shop Information", "topic": "Brakes", "question_text": "Brake fade occurs when:", "options": ["Brake fluid runs low", "Excessive heat reduces braking effectiveness, especially during prolonged hard braking", "The ABS system activates", "Brake pads are new and not yet broken in"], "correct_index": 1, "difficulty": 2, "explanation": "Brake fade occurs when brakes overheat (long downhill braking) and braking efficiency drops dramatically. Glazed brake pads, boiling brake fluid, or overheated rotors all contribute. Use engine braking on long descents.", "test_types": ["ASVAB"]},
    {"id": "AS054", "section": "Auto and Shop Information", "topic": "Transmission", "question_text": "The differential allows:", "options": ["The engine to connect to the transmission", "The left and right drive wheels to rotate at different speeds during turns", "The transmission to shift smoothly", "The driveshaft to transfer power to the axle"], "correct_index": 1, "difficulty": 2, "explanation": "The differential allows the outer wheel to rotate faster than the inner wheel during turns (the outer wheel travels a longer distance). Without a differential, turns would cause tire scrubbing and drivetrain binding.", "test_types": ["ASVAB"]},
    {"id": "AS055", "section": "Auto and Shop Information", "topic": "Fuel System", "question_text": "The oxygen (O2) sensor in an exhaust system measures:", "options": ["Engine oil temperature", "Exhaust gas temperature", "The amount of oxygen in exhaust gases to help the ECU adjust fuel mixture", "Carbon monoxide levels for emissions testing"], "correct_index": 2, "difficulty": 2, "explanation": "The O2 sensor tells the ECU (engine computer) whether the fuel mixture is rich (too much fuel) or lean (too little fuel). The ECU adjusts fuel injector duration accordingly for optimal combustion and emissions.", "test_types": ["ASVAB"]},
    {"id": "AS056", "section": "Auto and Shop Information", "topic": "Tools", "question_text": "A vise (bench vise) is used to:", "options": ["Hold work securely for cutting, filing, or other operations", "Measure the tightness of bolts", "Remove seized fasteners", "Cut metal pipe"], "correct_index": 0, "difficulty": 1, "explanation": "A bench vise clamps workpieces securely to the workbench, freeing both hands for filing, sawing, drilling, or bending. The jaws tighten with a screw. A vise is a fundamental shop tool.", "test_types": ["ASVAB"]},
    {"id": "AS057", "section": "Auto and Shop Information", "topic": "Engine", "question_text": "What is the purpose of the PCV (Positive Crankcase Ventilation) valve?", "options": ["Control coolant pressure", "Vent crankcase gases back to the intake manifold instead of releasing them to the atmosphere", "Regulate engine oil pressure", "Control the EGR system"], "correct_index": 1, "difficulty": 3, "explanation": "The PCV valve vents crankcase gases (blow-by gases past piston rings) into the intake manifold to be burned, rather than releasing them. This is an emissions control device and also helps prevent sludge buildup in the crankcase.", "test_types": ["ASVAB"]},
    {"id": "AS058", "section": "Auto and Shop Information", "topic": "Brakes", "question_text": "A 'spongy' or 'soft' brake pedal is usually caused by:", "options": ["Worn brake pads", "Air in the brake hydraulic lines", "Stuck brake caliper", "Loose wheel bearing"], "correct_index": 1, "difficulty": 2, "explanation": "Air in brake lines compresses (unlike hydraulic fluid, which doesn't), giving a spongy pedal feel. Proper braking requires bleeding the brake system to remove all air. Worn pads cause a low pedal, not a spongy one.", "test_types": ["ASVAB"]},
    {"id": "AS059", "section": "Auto and Shop Information", "topic": "Engine Components", "question_text": "Piston rings primarily serve to:", "options": ["Connect the piston to the connecting rod", "Seal combustion gases above the piston and control oil on cylinder walls", "Provide cushioning for the piston", "Measure piston position"], "correct_index": 1, "difficulty": 2, "explanation": "Piston rings (compression rings and oil control rings) seal the combustion chamber above the piston and scrape oil from cylinder walls. Worn rings cause oil burning (blue smoke) and compression loss.", "test_types": ["ASVAB"]},
    {"id": "AS060", "section": "Auto and Shop Information", "topic": "Tires", "question_text": "What does the number '205' represent in a tire size designation of 205/55R16?", "options": ["The rim diameter in inches", "The tire's width in millimeters", "The sidewall height in millimeters", "The load index"], "correct_index": 1, "difficulty": 3, "explanation": "In 205/55R16: 205 = section width in mm; 55 = aspect ratio (sidewall height as % of width); R = radial construction; 16 = rim diameter in inches. So this tire is 205mm wide on a 16-inch rim.", "test_types": ["ASVAB"]},
    {"id": "AS061", "section": "Auto and Shop Information", "topic": "Electrical System", "question_text": "When jump-starting a car, the correct order for connecting jumper cables is:", "options": ["Negative to dead battery first, then positive", "Positive to dead battery first, then positive to good battery, negative to good battery, negative to engine ground", "Both positives first, then both negatives", "Either order is fine as long as you are quick"], "correct_index": 1, "difficulty": 2, "explanation": "Correct order: + dead → + good → - good → engine ground (not battery) on dead car. The last connection is away from the battery to avoid sparking near battery gases. Remove in reverse order.", "test_types": ["ASVAB"]},
    {"id": "AS062", "section": "Auto and Shop Information", "topic": "Tools", "question_text": "A file is used to:", "options": ["Cut material quickly by sawing", "Remove small amounts of material by abrasion to shape, smooth, or deburr metal", "Drill holes in metal", "Bend sheet metal"], "correct_index": 1, "difficulty": 1, "explanation": "Files are hardened steel tools with cutting teeth used to remove material by abrasion. Different cuts (bastard, second, smooth) and profiles (flat, round, half-round, triangular) suit different operations.", "test_types": ["ASVAB"]},
    {"id": "AS063", "section": "Auto and Shop Information", "topic": "Engine", "question_text": "The exhaust manifold collects:", "options": ["Intake air before it enters cylinders", "Burned exhaust gases from cylinders and channels them to the exhaust system", "Coolant for distribution to the engine block", "Oil for lubrication of valves"], "correct_index": 1, "difficulty": 1, "explanation": "The exhaust manifold bolts to the cylinder head and collects exhaust gases from all cylinders, routing them into the exhaust pipe, catalytic converter, muffler, and out the tailpipe.", "test_types": ["ASVAB"]},
    {"id": "AS064", "section": "Auto and Shop Information", "topic": "Brakes", "question_text": "Brake rotors should be replaced or resurfaced when they:", "options": ["Develop a slight surface rust after rain", "Become grooved or worn below the minimum thickness specification", "Show any discoloration from heat", "Have been used for 12 months regardless of condition"], "correct_index": 1, "difficulty": 2, "explanation": "Rotors need replacement or resurfacing when they develop grooves (from worn-through pads), warping (causes pedal pulsation), or when they wear below minimum thickness spec. Surface rust after rain is normal and clears after a few brake applications.", "test_types": ["ASVAB"]},
    {"id": "AS065", "section": "Auto and Shop Information", "topic": "Fuel System", "question_text": "A catalytic converter is part of the exhaust system and its purpose is to:", "options": ["Improve fuel economy", "Muffle exhaust noise", "Convert harmful exhaust pollutants (HC, CO, NOx) into less harmful gases", "Increase exhaust flow"], "correct_index": 2, "difficulty": 2, "explanation": "The catalytic converter uses platinum, palladium, and rhodium catalysts to convert hydrocarbons (HC), carbon monoxide (CO), and nitrogen oxides (NOx) into carbon dioxide (CO2), water, and nitrogen.", "test_types": ["ASVAB"]},
    {"id": "AS066", "section": "Auto and Shop Information", "topic": "Lubrication", "question_text": "Engine oil viscosity ratings (like 5W-30) indicate:", "options": ["The oil's color and purity", "The oil's flow characteristics at cold startup (first number) and operating temperature (second number)", "The oil's chemical composition", "How often the oil should be changed"], "correct_index": 1, "difficulty": 2, "explanation": "In 5W-30: '5W' is the winter (cold) viscosity — lower number flows better when cold, for easier cold starts. '30' is the hot viscosity — higher number means thicker oil at operating temperature. Multi-grade oils work in wide temperature ranges.", "test_types": ["ASVAB"]},
    {"id": "AS067", "section": "Auto and Shop Information", "topic": "Tools", "question_text": "Which tool would best measure the inside diameter of an engine cylinder bore?", "options": ["Outside micrometer", "Feeler gauge", "Inside micrometer or bore gauge", "Vernier caliper"], "correct_index": 2, "difficulty": 2, "explanation": "An inside micrometer or dial bore gauge measures cylinder bore diameter precisely to check for wear, taper, and out-of-round conditions. A regular outside micrometer can't reach inside a bore.", "test_types": ["ASVAB"]},
    {"id": "AS068", "section": "Auto and Shop Information", "topic": "Transmission", "question_text": "A vehicle equipped with 4WD (four-wheel drive) has power sent to:", "options": ["All four wheels simultaneously via a transfer case", "The front two wheels only", "The rear two wheels only", "Whichever wheel has the most traction automatically"], "correct_index": 0, "difficulty": 1, "explanation": "4WD uses a transfer case to split power between front and rear axles, driving all four wheels. It is typically engaged manually for off-road use. AWD (all-wheel drive) automatically distributes power and is always active.", "test_types": ["ASVAB"]},
    {"id": "AS069", "section": "Auto and Shop Information", "topic": "Engine Cycles", "question_text": "In a 4-stroke engine, how many crankshaft revolutions occur per complete engine cycle (all 4 strokes)?", "options": ["One revolution", "Two revolutions", "Four revolutions", "Half a revolution"], "correct_index": 1, "difficulty": 3, "explanation": "Each piston stroke corresponds to half a crankshaft revolution. Four strokes = 2 full crankshaft revolutions per complete power cycle. The power stroke occurs every other revolution per cylinder.", "test_types": ["ASVAB"]},
    {"id": "AS070", "section": "Auto and Shop Information", "topic": "Cooling System", "question_text": "The radiator cap maintains pressure in the cooling system to:", "options": ["Keep coolant from leaking out", "Increase the coolant's boiling point above 212°F (100°C)", "Regulate coolant flow rate", "Prevent air from entering the system"], "correct_index": 1, "difficulty": 2, "explanation": "Pressurizing the cooling system raises the coolant's boiling point (typically to 250-265°F / 121-130°C). This prevents boiling in high-temperature areas like near the exhaust valves. Never open a hot radiator cap — steam will erupt.", "test_types": ["ASVAB"]},
    {"id": "AS071", "section": "Auto and Shop Information", "topic": "Brakes", "question_text": "A brake proportioning valve:", "options": ["Adjusts brake fluid viscosity", "Limits rear brake pressure to prevent rear wheel lockup before front lockup", "Equalizes pressure to all four wheels equally", "Controls the ABS modulator"], "correct_index": 1, "difficulty": 3, "explanation": "The proportioning valve reduces hydraulic pressure to the rear brakes relative to the front. During braking, weight transfers forward, reducing rear wheel traction. Less rear brake pressure prevents rear lockup and spinning.", "test_types": ["ASVAB"]},
    {"id": "AS072", "section": "Auto and Shop Information", "topic": "Engine Components", "question_text": "The intake manifold distributes:", "options": ["Oil to the valve train", "Air or air-fuel mixture from the throttle body to each cylinder's intake port", "Coolant to the cylinder head", "Exhaust gases to the muffler"], "correct_index": 1, "difficulty": 2, "explanation": "The intake manifold routes air (in fuel-injected engines) or air-fuel mixture (in carbureted engines) from the throttle body to each cylinder's intake port. Manifold vacuum is also used for brake boosters and vacuum accessories.", "test_types": ["ASVAB"]},
    {"id": "AS073", "section": "Auto and Shop Information", "topic": "Tools", "question_text": "When using a socket set, an extension bar is used to:", "options": ["Increase torque capacity", "Reach fasteners in recessed or deep locations", "Convert metric to SAE sizes", "Prevent over-torquing"], "correct_index": 1, "difficulty": 1, "explanation": "Extension bars fit between the ratchet handle and the socket to reach bolts in deep recesses, pockets, or areas where the ratchet won't fit. Extensions come in various lengths (short, medium, long).", "test_types": ["ASVAB"]},
    {"id": "AS074", "section": "Auto and Shop Information", "topic": "Tires", "question_text": "What is a tire 'blowout' and what is a common cause?", "options": ["A tire that slowly deflates over time; caused by a leaking valve stem", "A sudden, rapid loss of tire air pressure; often caused by a cut, impact damage, or extreme overloading of an under-inflated tire", "A tire that separates from the rim; caused by incorrect mounting", "A tire that becomes flat from a nail; caused by punctures"], "correct_index": 1, "difficulty": 2, "explanation": "A blowout is sudden, catastrophic air loss — dangerous at highway speeds. Common causes: driving over sharp objects or potholes at speed, extreme overloading, or running severely under-inflated tires that overheat and fail.", "test_types": ["ASVAB"]},
    {"id": "AS075", "section": "Auto and Shop Information", "topic": "Fuel System", "question_text": "The throttle body in a modern fuel-injected engine controls:", "options": ["The amount of fuel injected", "The amount of air entering the engine (engine speed/load)", "The ignition timing", "The exhaust gas recirculation"], "correct_index": 1, "difficulty": 2, "explanation": "The throttle body contains a butterfly valve (throttle plate) that opens when you press the accelerator, allowing more air into the engine. More air triggers more fuel injection for more power. Modern vehicles use electronic throttle control (drive-by-wire).", "test_types": ["ASVAB"]},
]

if __name__ == "__main__":
    print(f"AS question count: {len(AS_QUESTIONS)}")
