#!/usr/bin/env python3
"""General Science questions — 100 questions"""

GS_QUESTIONS = [
    # === LIFE SCIENCE: Cell Biology (WK001-WK020 → GS001-GS020) ===
    {"id": "GS001", "section": "General Science", "topic": "Cell Biology", "question_text": "Which organelle is known as the powerhouse of the cell because it produces ATP?", "options": ["Nucleus", "Ribosome", "Mitochondria", "Vacuole"], "correct_index": 2, "difficulty": 1, "explanation": "Mitochondria produce ATP through cellular respiration, hence the 'powerhouse' nickname. The nucleus contains DNA. Ribosomes make proteins. Vacuoles store water and waste.", "test_types": ["ASVAB"]},
    {"id": "GS002", "section": "General Science", "topic": "Cell Biology", "question_text": "Which organelle contains the cell's genetic information (DNA)?", "options": ["Mitochondria", "Nucleus", "Cell membrane", "Ribosome"], "correct_index": 1, "difficulty": 1, "explanation": "The nucleus is the control center of the cell and houses the DNA. Mitochondria have their own small DNA but the main genetic information is in the nucleus.", "test_types": ["ASVAB"]},
    {"id": "GS003", "section": "General Science", "topic": "Cell Biology", "question_text": "Chloroplasts are found in plant cells but NOT animal cells. What is their function?", "options": ["Produce ATP from sugar", "Carry out photosynthesis", "Store genetic information", "Control cell division"], "correct_index": 1, "difficulty": 1, "explanation": "Chloroplasts contain chlorophyll and perform photosynthesis, converting sunlight into glucose. Mitochondria produce ATP from sugar. The nucleus stores DNA.", "test_types": ["ASVAB"]},
    {"id": "GS004", "section": "General Science", "topic": "Cell Biology", "question_text": "What structure controls what enters and exits a cell?", "options": ["Cell wall", "Nucleus", "Cell membrane", "Vacuole"], "correct_index": 2, "difficulty": 1, "explanation": "The cell membrane (plasma membrane) is selectively permeable and controls what enters and exits the cell. The cell wall provides structural support in plants. The vacuole stores materials.", "test_types": ["ASVAB"]},
    {"id": "GS005", "section": "General Science", "topic": "Cell Biology", "question_text": "Ribosomes are responsible for:", "options": ["Storing energy", "Producing proteins", "Digesting waste", "Transporting materials"], "correct_index": 1, "difficulty": 1, "explanation": "Ribosomes read mRNA and assemble amino acids into proteins — they are the cell's protein factories. Mitochondria store/produce energy. Lysosomes digest waste.", "test_types": ["ASVAB"]},
    {"id": "GS006", "section": "General Science", "topic": "Cell Biology", "question_text": "Which of the following is found in plant cells but NOT in animal cells?", "options": ["Mitochondria", "Cell wall", "Nucleus", "Ribosome"], "correct_index": 1, "difficulty": 1, "explanation": "Plant cells have a rigid cell wall made of cellulose outside the membrane. Animal cells lack a cell wall. Both have mitochondria, nuclei, and ribosomes.", "test_types": ["ASVAB"]},
    {"id": "GS007", "section": "General Science", "topic": "Cell Biology", "question_text": "What is the function of the vacuole in a plant cell?", "options": ["Produce energy", "Store water, nutrients, and waste", "Perform photosynthesis", "Synthesize proteins"], "correct_index": 1, "difficulty": 2, "explanation": "The large central vacuole in plant cells stores water (providing turgor pressure), nutrients, and waste products. Photosynthesis occurs in chloroplasts. Protein synthesis occurs at ribosomes.", "test_types": ["ASVAB"]},

    # === LIFE SCIENCE: Cell Division ===
    {"id": "GS008", "section": "General Science", "topic": "Cell Division", "question_text": "Mitosis produces cells used for:", "options": ["Sexual reproduction", "Growth and repair", "Egg and sperm production", "Genetic variation"], "correct_index": 1, "difficulty": 1, "explanation": "Mitosis produces two identical daughter cells for growth, repair, and asexual reproduction. Meiosis produces sex cells (eggs and sperm) with half the normal chromosomes.", "test_types": ["ASVAB"]},
    {"id": "GS009", "section": "General Science", "topic": "Cell Division", "question_text": "Meiosis differs from mitosis in that meiosis:", "options": ["Produces 2 identical cells", "Produces 4 cells with half the chromosomes", "Only occurs in bacteria", "Does not involve DNA"], "correct_index": 1, "difficulty": 2, "explanation": "Meiosis produces 4 genetically unique cells (gametes) each with half the original chromosome number (haploid). Mitosis produces 2 genetically identical diploid cells.", "test_types": ["ASVAB"]},
    {"id": "GS010", "section": "General Science", "topic": "Cell Division", "question_text": "A cell with 46 chromosomes undergoes mitosis. How many chromosomes does each daughter cell have?", "options": ["23", "46", "92", "12"], "correct_index": 1, "difficulty": 2, "explanation": "Mitosis produces two genetically identical daughter cells, each with the same number of chromosomes as the parent — 46. Meiosis would produce cells with 23.", "test_types": ["ASVAB"]},

    # === LIFE SCIENCE: DNA/Genetics ===
    {"id": "GS011", "section": "General Science", "topic": "Genetics", "question_text": "DNA is described as a double helix. What holds the two strands together?", "options": ["Covalent bonds between sugars", "Hydrogen bonds between base pairs", "Ionic bonds between phosphates", "Protein bridges"], "correct_index": 1, "difficulty": 2, "explanation": "The two DNA strands are held together by hydrogen bonds between complementary base pairs: adenine (A) pairs with thymine (T), and cytosine (C) pairs with guanine (G).", "test_types": ["ASVAB"]},
    {"id": "GS012", "section": "General Science", "topic": "Genetics", "question_text": "In DNA, adenine always pairs with:", "options": ["Cytosine", "Guanine", "Thymine", "Uracil"], "correct_index": 2, "difficulty": 1, "explanation": "In DNA, the base pairing rules are: A pairs with T, and C pairs with G. Uracil replaces thymine only in RNA (not DNA).", "test_types": ["ASVAB"]},
    {"id": "GS013", "section": "General Science", "topic": "Genetics", "question_text": "A dominant allele will always:", "options": ["Be passed to all offspring", "Be expressed when present", "Cause a genetic disorder", "Replace a recessive allele"], "correct_index": 1, "difficulty": 2, "explanation": "A dominant allele is expressed (shows its trait) whenever it is present, even if only one copy exists. A recessive allele is only expressed when two copies are present.", "test_types": ["ASVAB"]},
    {"id": "GS014", "section": "General Science", "topic": "Genetics", "question_text": "In a Punnett square cross between two Tt parents (T = tall is dominant), what fraction of offspring will be short?", "options": ["1/4", "1/2", "3/4", "0"], "correct_index": 0, "difficulty": 2, "explanation": "Tt x Tt produces TT, Tt, Tt, and tt in a 1:2:1 ratio. Only tt (homozygous recessive) is short, so 1 out of 4 or 25% will be short.", "test_types": ["ASVAB"]},

    # === LIFE SCIENCE: Taxonomy ===
    {"id": "GS015", "section": "General Science", "topic": "Taxonomy", "question_text": "What is the correct order of biological classification from broadest to most specific?", "options": ["Kingdom, Phylum, Class, Order, Family, Genus, Species", "Species, Genus, Family, Order, Class, Phylum, Kingdom", "Kingdom, Class, Phylum, Order, Family, Genus, Species", "Domain, Kingdom, Order, Class, Phylum, Family, Species"], "correct_index": 0, "difficulty": 2, "explanation": "The hierarchy from broadest to most specific is: Kingdom, Phylum, Class, Order, Family, Genus, Species — remembered by the mnemonic 'King Philip Came Over For Good Soup' (KPCOFGS).", "test_types": ["ASVAB"]},
    {"id": "GS016", "section": "General Science", "topic": "Taxonomy", "question_text": "Two organisms belong to the same genus but different species. How closely related are they?", "options": ["Not related at all", "Very closely related", "Distantly related", "Identical genetically"], "correct_index": 1, "difficulty": 2, "explanation": "Genus is the second most specific level of classification. Organisms in the same genus are very closely related, sharing more traits than organisms at any higher classification level.", "test_types": ["ASVAB"]},

    # === LIFE SCIENCE: Photosynthesis ===
    {"id": "GS017", "section": "General Science", "topic": "Photosynthesis", "question_text": "What are the raw materials (reactants) of photosynthesis?", "options": ["Glucose and oxygen", "Carbon dioxide and water", "ATP and oxygen", "Glucose and carbon dioxide"], "correct_index": 1, "difficulty": 1, "explanation": "Photosynthesis equation: CO2 + H2O + sunlight → glucose + O2. Carbon dioxide and water are the reactants. Glucose and oxygen are the products.", "test_types": ["ASVAB"]},
    {"id": "GS018", "section": "General Science", "topic": "Photosynthesis", "question_text": "Chlorophyll is the green pigment in plants that captures:", "options": ["Water", "Carbon dioxide", "Sunlight", "Nutrients from soil"], "correct_index": 2, "difficulty": 1, "explanation": "Chlorophyll absorbs sunlight (primarily red and blue wavelengths) to power photosynthesis. Plants absorb CO2 through stomata and water through roots, but chlorophyll specifically captures light energy.", "test_types": ["ASVAB"]},

    # === LIFE SCIENCE: Cellular Respiration ===
    {"id": "GS019", "section": "General Science", "topic": "Cellular Respiration", "question_text": "Cellular respiration primarily occurs in which organelle?", "options": ["Nucleus", "Chloroplast", "Mitochondria", "Ribosome"], "correct_index": 2, "difficulty": 1, "explanation": "Cellular respiration — converting glucose and oxygen into CO2, water, and ATP energy — occurs in the mitochondria. Chloroplasts perform photosynthesis (the reverse process).", "test_types": ["ASVAB"]},
    {"id": "GS020", "section": "General Science", "topic": "Cellular Respiration", "question_text": "The equation for cellular respiration is:", "options": ["CO2 + H2O → Glucose + O2", "Glucose + O2 → CO2 + H2O + ATP", "Glucose + CO2 → O2 + H2O", "ATP + O2 → Glucose + CO2"], "correct_index": 1, "difficulty": 2, "explanation": "Cellular respiration: Glucose + O2 → CO2 + H2O + ATP. This is essentially the reverse of photosynthesis. It releases chemical energy stored in glucose as usable ATP.", "test_types": ["ASVAB"]},

    # === LIFE SCIENCE: Ecosystems ===
    {"id": "GS021", "section": "General Science", "topic": "Ecosystems", "question_text": "In a food chain, organisms that make their own food from sunlight are called:", "options": ["Consumers", "Decomposers", "Producers", "Predators"], "correct_index": 2, "difficulty": 1, "explanation": "Producers (plants, algae) make their own food via photosynthesis and form the base of the food chain. Consumers eat other organisms. Decomposers break down dead matter.", "test_types": ["ASVAB"]},
    {"id": "GS022", "section": "General Science", "topic": "Ecosystems", "question_text": "According to the 10% rule, if grass stores 10,000 calories, how much energy is available to a primary consumer (rabbit)?", "options": ["10,000 calories", "1,000 calories", "100 calories", "10 calories"], "correct_index": 1, "difficulty": 2, "explanation": "The 10% rule states that only 10% of energy passes from one trophic level to the next. 10% of 10,000 = 1,000 calories available to the primary consumer.", "test_types": ["ASVAB"]},
    {"id": "GS023", "section": "General Science", "topic": "Ecosystems", "question_text": "Bacteria and fungi that break down dead organic matter are called:", "options": ["Producers", "Consumers", "Decomposers", "Parasites"], "correct_index": 2, "difficulty": 1, "explanation": "Decomposers (bacteria, fungi) break down dead organisms and waste, returning nutrients to the soil. They are essential to nutrient cycling in ecosystems.", "test_types": ["ASVAB"]},
    {"id": "GS024", "section": "General Science", "topic": "Ecosystems", "question_text": "Which level of the energy pyramid contains the most stored energy?", "options": ["Top predators", "Secondary consumers", "Primary consumers", "Producers"], "correct_index": 3, "difficulty": 2, "explanation": "Producers (plants) at the base of the energy pyramid contain the most energy. Each level up loses 90% of the energy, so the base has the most and the apex (top predators) has the least.", "test_types": ["ASVAB"]},

    # === LIFE SCIENCE: Evolution ===
    {"id": "GS025", "section": "General Science", "topic": "Evolution", "question_text": "Natural selection favors organisms that:", "options": ["Are the largest and strongest", "Reproduce before others", "Are best adapted to their environment", "Live the longest"], "correct_index": 2, "difficulty": 2, "explanation": "Natural selection favors traits that improve survival and reproduction in a specific environment. Being large, fast, or long-lived matters only if those traits help in that specific environment.", "test_types": ["ASVAB"]},
    {"id": "GS026", "section": "General Science", "topic": "Evolution", "question_text": "An adaptation is best described as:", "options": ["A learned behavior", "A physical change during an organism's lifetime", "A heritable trait that increases survival and reproduction", "A mutation that always benefits the organism"], "correct_index": 2, "difficulty": 2, "explanation": "An adaptation is a heritable trait that increases an organism's fitness (survival and reproduction) in its environment. It must be inherited to be passed to offspring via natural selection.", "test_types": ["ASVAB"]},

    # === CHEMISTRY: Atomic Structure ===
    {"id": "GS027", "section": "General Science", "topic": "Atomic Structure", "question_text": "The atomic number of an element is equal to the number of:", "options": ["Neutrons in the nucleus", "Protons in the nucleus", "Electrons and neutrons combined", "Electrons in the outer shell"], "correct_index": 1, "difficulty": 1, "explanation": "The atomic number equals the number of protons in the nucleus, which also defines what element it is. In a neutral atom, the number of electrons equals the number of protons.", "test_types": ["ASVAB"]},
    {"id": "GS028", "section": "General Science", "topic": "Atomic Structure", "question_text": "What is the mass number of an atom?", "options": ["Number of protons only", "Number of neutrons only", "Sum of protons and neutrons", "Sum of protons, neutrons, and electrons"], "correct_index": 2, "difficulty": 1, "explanation": "Mass number = protons + neutrons. Electrons have negligible mass, so they are not included. For example, carbon has 6 protons and 6 neutrons, giving a mass number of 12.", "test_types": ["ASVAB"]},
    {"id": "GS029", "section": "General Science", "topic": "Atomic Structure", "question_text": "Which subatomic particle has a negative charge?", "options": ["Proton", "Neutron", "Electron", "Nucleus"], "correct_index": 2, "difficulty": 1, "explanation": "Electrons have a negative charge (-1) and orbit the nucleus. Protons have a positive charge (+1). Neutrons have no charge (neutral). The nucleus is not a subatomic particle.", "test_types": ["ASVAB"]},
    {"id": "GS030", "section": "General Science", "topic": "Atomic Structure", "question_text": "Two atoms of the same element with different numbers of neutrons are called:", "options": ["Isotopes", "Ions", "Isomers", "Allotropes"], "correct_index": 0, "difficulty": 2, "explanation": "Isotopes are atoms of the same element (same proton count) with different numbers of neutrons, giving different mass numbers. Carbon-12 and Carbon-14 are common isotopes.", "test_types": ["ASVAB"]},

    # === CHEMISTRY: Periodic Table ===
    {"id": "GS031", "section": "General Science", "topic": "Periodic Table", "question_text": "Elements in the same vertical column (group) of the periodic table:", "options": ["Have the same mass number", "Have similar chemical properties", "Are all metals", "Have the same number of neutrons"], "correct_index": 1, "difficulty": 2, "explanation": "Elements in the same group (column) have the same number of valence electrons and therefore similar chemical properties. For example, all Group 1 elements (alkali metals) react vigorously with water.", "test_types": ["ASVAB"]},
    {"id": "GS032", "section": "General Science", "topic": "Periodic Table", "question_text": "The noble gases (Group 18) are chemically:", "options": ["Very reactive", "Slightly reactive", "Inert (unreactive)", "Only reactive with metals"], "correct_index": 2, "difficulty": 1, "explanation": "Noble gases (helium, neon, argon, etc.) have a full outer electron shell, making them chemically inert — they rarely form compounds. This is why they are used in light bulbs and balloons.", "test_types": ["ASVAB"]},
    {"id": "GS033", "section": "General Science", "topic": "Periodic Table", "question_text": "Metals are located on which side of the periodic table?", "options": ["Right side", "Left side and center", "Top row only", "Bottom rows only"], "correct_index": 1, "difficulty": 1, "explanation": "Metals occupy the left side and the central block (transition metals) of the periodic table. Non-metals are on the upper right. The dividing line is the 'staircase' or metalloid line.", "test_types": ["ASVAB"]},

    # === CHEMISTRY: Chemical Bonds ===
    {"id": "GS034", "section": "General Science", "topic": "Chemical Bonds", "question_text": "An ionic bond forms when:", "options": ["Two nonmetals share electrons", "A metal transfers electrons to a nonmetal", "Two metals combine", "Atoms share protons"], "correct_index": 1, "difficulty": 2, "explanation": "Ionic bonds form when a metal loses electrons (becoming a positive ion) and transfers them to a nonmetal (which becomes a negative ion). The opposite charges attract. Example: sodium + chlorine → NaCl.", "test_types": ["ASVAB"]},
    {"id": "GS035", "section": "General Science", "topic": "Chemical Bonds", "question_text": "A covalent bond forms when:", "options": ["A metal gives electrons to a nonmetal", "Two atoms share electrons", "Ions are attracted to each other", "An atom gains extra neutrons"], "correct_index": 1, "difficulty": 2, "explanation": "Covalent bonds form when two atoms (usually nonmetals) share pairs of electrons. Water (H2O) and oxygen gas (O2) are held together by covalent bonds.", "test_types": ["ASVAB"]},

    # === CHEMISTRY: Acids and Bases ===
    {"id": "GS036", "section": "General Science", "topic": "Acids and Bases", "question_text": "On the pH scale, a solution with a pH of 3 is:", "options": ["A strong base", "A weak base", "Neutral", "An acid"], "correct_index": 3, "difficulty": 1, "explanation": "The pH scale runs from 0 to 14. pH below 7 = acid, pH 7 = neutral, pH above 7 = base. pH 3 is acidic. The lower the number, the stronger the acid.", "test_types": ["ASVAB"]},
    {"id": "GS037", "section": "General Science", "topic": "Acids and Bases", "question_text": "What is the pH of pure water?", "options": ["0", "5", "7", "14"], "correct_index": 2, "difficulty": 1, "explanation": "Pure water is neutral with a pH of 7. Below 7 is acidic (like vinegar at ~3), above 7 is basic (like bleach at ~12).", "test_types": ["ASVAB"]},
    {"id": "GS038", "section": "General Science", "topic": "Acids and Bases", "question_text": "When an acid and base are mixed in equal amounts, the result is:", "options": ["A stronger acid", "A stronger base", "Neutralization, producing a salt and water", "Combustion"], "correct_index": 2, "difficulty": 2, "explanation": "Neutralization occurs when an acid and base react, producing a salt and water. For example, HCl (acid) + NaOH (base) → NaCl (table salt) + H2O.", "test_types": ["ASVAB"]},

    # === CHEMISTRY: States of Matter ===
    {"id": "GS039", "section": "General Science", "topic": "States of Matter", "question_text": "When a liquid changes to a gas, the process is called:", "options": ["Condensation", "Sublimation", "Evaporation", "Melting"], "correct_index": 2, "difficulty": 1, "explanation": "Evaporation (or boiling at the boiling point) is the liquid-to-gas transition. Condensation is gas-to-liquid. Sublimation is solid-to-gas. Melting is solid-to-liquid.", "test_types": ["ASVAB"]},
    {"id": "GS040", "section": "General Science", "topic": "States of Matter", "question_text": "A reaction that absorbs heat from its surroundings is called:", "options": ["Exothermic", "Endothermic", "Isothermal", "Combustion"], "correct_index": 1, "difficulty": 2, "explanation": "Endothermic reactions absorb heat (think 'endo' = inside, taking heat in). Exothermic reactions release heat ('exo' = outside, giving heat out). Burning is exothermic.", "test_types": ["ASVAB"]},

    # === CHEMISTRY: Mixtures ===
    {"id": "GS041", "section": "General Science", "topic": "Matter Classification", "question_text": "Which of the following is a pure element?", "options": ["Water (H2O)", "Salt (NaCl)", "Oxygen gas (O2)", "Air"], "correct_index": 2, "difficulty": 1, "explanation": "Oxygen gas (O2) consists of only one type of atom (oxygen), making it a pure element. Water is a compound (two elements bonded). Salt is a compound. Air is a mixture.", "test_types": ["ASVAB"]},
    {"id": "GS042", "section": "General Science", "topic": "Matter Classification", "question_text": "Salt water is an example of a:", "options": ["Pure element", "Compound", "Mixture", "Crystal"], "correct_index": 2, "difficulty": 1, "explanation": "Salt water is a mixture — the salt and water are not chemically combined and can be separated by evaporation. A compound has elements chemically bonded together and cannot be separated physically.", "test_types": ["ASVAB"]},

    # === PHYSICAL SCIENCE: Newton's Laws ===
    {"id": "GS043", "section": "General Science", "topic": "Newton's Laws", "question_text": "Newton's first law states that an object at rest will remain at rest unless:", "options": ["It is on a frictionless surface", "An unbalanced force acts on it", "It reaches its natural state", "Gravity is removed"], "correct_index": 1, "difficulty": 1, "explanation": "Newton's first law (inertia): objects remain in their current state of motion unless acted upon by an unbalanced (net) force. This is why you need force to start, stop, or change direction of motion.", "test_types": ["ASVAB"]},
    {"id": "GS044", "section": "General Science", "topic": "Newton's Laws", "question_text": "Newton's third law states that for every action, there is:", "options": ["An equal reaction in the same direction", "A greater reaction in the opposite direction", "An equal and opposite reaction", "A smaller reaction in any direction"], "correct_index": 2, "difficulty": 1, "explanation": "Newton's third law: for every action force, there is an equal and opposite reaction force. When you push a wall, the wall pushes back with equal force. This explains rocket propulsion.", "test_types": ["ASVAB"]},

    # === PHYSICAL SCIENCE: Waves ===
    {"id": "GS045", "section": "General Science", "topic": "Waves", "question_text": "If a wave has a frequency of 5 Hz and a wavelength of 4 meters, what is its speed?", "options": ["1.25 m/s", "9 m/s", "20 m/s", "0.8 m/s"], "correct_index": 2, "difficulty": 2, "explanation": "Wave speed = frequency × wavelength. Speed = 5 Hz × 4 m = 20 m/s. This formula (v = fλ) applies to all waves.", "test_types": ["ASVAB"]},
    {"id": "GS046", "section": "General Science", "topic": "Waves", "question_text": "The amplitude of a wave represents:", "options": ["The distance between two crests", "The number of waves per second", "The maximum displacement from rest position", "The speed of the wave"], "correct_index": 2, "difficulty": 2, "explanation": "Amplitude is the maximum displacement from the rest (equilibrium) position — the height of a crest or depth of a trough. Greater amplitude means more energy. Wavelength is crest-to-crest distance. Frequency is waves per second.", "test_types": ["ASVAB"]},
    {"id": "GS047", "section": "General Science", "topic": "Waves", "question_text": "Sound travels fastest through which medium?", "options": ["Vacuum (empty space)", "Air", "Water", "Steel"], "correct_index": 3, "difficulty": 2, "explanation": "Sound travels faster in denser, more rigid materials. Speed: steel (~5,100 m/s) > water (~1,500 m/s) > air (~340 m/s). Sound cannot travel through a vacuum at all (no medium).", "test_types": ["ASVAB"]},

    # === PHYSICAL SCIENCE: Electromagnetic Spectrum ===
    {"id": "GS048", "section": "General Science", "topic": "Electromagnetic Spectrum", "question_text": "Which type of electromagnetic radiation has the highest frequency?", "options": ["Radio waves", "Visible light", "X-rays", "Gamma rays"], "correct_index": 3, "difficulty": 2, "explanation": "The electromagnetic spectrum from lowest to highest frequency: radio → microwave → infrared → visible → UV → X-ray → gamma. Gamma rays have the highest frequency (and energy).", "test_types": ["ASVAB"]},
    {"id": "GS049", "section": "General Science", "topic": "Electromagnetic Spectrum", "question_text": "Ultraviolet (UV) radiation from the sun is mostly blocked by which layer of the atmosphere?", "options": ["Troposphere", "Stratosphere (ozone layer)", "Mesosphere", "Thermosphere"], "correct_index": 1, "difficulty": 2, "explanation": "The stratosphere contains the ozone layer (O3), which absorbs most UV radiation from the sun. The troposphere is where weather occurs. The mesosphere burns up meteors.", "test_types": ["ASVAB"]},
    {"id": "GS050", "section": "General Science", "topic": "Electromagnetic Spectrum", "question_text": "Visible light contains all the colors of the rainbow. From lowest to highest frequency, they are:", "options": ["Violet, indigo, blue, green, yellow, orange, red", "Red, orange, yellow, green, blue, indigo, violet", "Red, yellow, blue, orange, green, indigo, violet", "Blue, green, red, yellow, orange, violet, indigo"], "correct_index": 1, "difficulty": 2, "explanation": "ROYGBIV — Red, Orange, Yellow, Green, Blue, Indigo, Violet — goes from lowest frequency (longest wavelength) to highest frequency (shortest wavelength). Red light bends the least through a prism.", "test_types": ["ASVAB"]},

    # === PHYSICAL SCIENCE: Light ===
    {"id": "GS051", "section": "General Science", "topic": "Light", "question_text": "When light bends as it passes from one medium to another, the process is called:", "options": ["Reflection", "Refraction", "Diffraction", "Absorption"], "correct_index": 1, "difficulty": 1, "explanation": "Refraction is the bending of light as it passes from one medium to another of different density (like air to water). This is why a pencil in a glass of water appears bent. Reflection is light bouncing off a surface.", "test_types": ["ASVAB"]},
    {"id": "GS052", "section": "General Science", "topic": "Light", "question_text": "When light bounces off a mirror, the process is called:", "options": ["Refraction", "Absorption", "Reflection", "Diffraction"], "correct_index": 2, "difficulty": 1, "explanation": "Reflection is when light bounces off a surface. Mirrors provide regular (specular) reflection where the angle of incidence equals the angle of reflection. Refraction is bending through a medium.", "test_types": ["ASVAB"]},

    # === PHYSICAL SCIENCE: Work and Energy ===
    {"id": "GS053", "section": "General Science", "topic": "Work and Energy", "question_text": "The formula for work is W = F × d. If a force of 10 newtons moves an object 5 meters, how much work was done?", "options": ["2 joules", "15 joules", "50 joules", "0.5 joules"], "correct_index": 2, "difficulty": 2, "explanation": "Work = Force × distance = 10 N × 5 m = 50 joules. Work is only done when the force moves an object in the direction of the force. The unit of work is the joule (J).", "test_types": ["ASVAB"]},

    # === PHYSICAL SCIENCE: Heat Transfer ===
    {"id": "GS054", "section": "General Science", "topic": "Heat Transfer", "question_text": "Heat transfer through direct contact between objects is called:", "options": ["Convection", "Radiation", "Conduction", "Insulation"], "correct_index": 2, "difficulty": 1, "explanation": "Conduction is heat transfer through direct contact, molecule to molecule. Convection transfers heat through fluid movement. Radiation transfers heat through electromagnetic waves (like sunlight).", "test_types": ["ASVAB"]},
    {"id": "GS055", "section": "General Science", "topic": "Heat Transfer", "question_text": "The Sun heats the Earth primarily through:", "options": ["Conduction", "Convection", "Radiation", "Induction"], "correct_index": 2, "difficulty": 1, "explanation": "The Sun heats the Earth through radiation — electromagnetic waves that travel through the vacuum of space. Conduction requires direct contact. Convection requires a fluid medium.", "test_types": ["ASVAB"]},

    # === EARTH SCIENCE: Atmosphere ===
    {"id": "GS056", "section": "General Science", "topic": "Atmosphere", "question_text": "In which layer of the atmosphere does weather occur?", "options": ["Stratosphere", "Mesosphere", "Thermosphere", "Troposphere"], "correct_index": 3, "difficulty": 1, "explanation": "The troposphere is the lowest layer of the atmosphere and is where all weather occurs. The stratosphere contains the ozone layer. The mesosphere burns up meteors. The thermosphere contains the aurora.", "test_types": ["ASVAB"]},
    {"id": "GS057", "section": "General Science", "topic": "Atmosphere", "question_text": "The ozone layer, which protects Earth from UV radiation, is in the:", "options": ["Troposphere", "Stratosphere", "Mesosphere", "Thermosphere"], "correct_index": 1, "difficulty": 1, "explanation": "The ozone layer is in the stratosphere, approximately 15-35 km above Earth's surface. Ozone (O3) absorbs harmful UV radiation. The troposphere is below it, where we live and where weather happens.", "test_types": ["ASVAB"]},
    {"id": "GS058", "section": "General Science", "topic": "Atmosphere", "question_text": "Which layer of the atmosphere burns up most meteoroids before they reach Earth?", "options": ["Troposphere", "Stratosphere", "Mesosphere", "Exosphere"], "correct_index": 2, "difficulty": 2, "explanation": "The mesosphere (50-80 km altitude) is where most meteoroids burn up due to friction with air molecules, creating what we see as 'shooting stars.' The thermosphere is above it.", "test_types": ["ASVAB"]},

    # === EARTH SCIENCE: Rocks ===
    {"id": "GS059", "section": "General Science", "topic": "Rock Cycle", "question_text": "Igneous rocks form from:", "options": ["Layers of sediment compressed over time", "Melted rock (magma or lava) that has cooled", "Existing rocks changed by heat and pressure", "Shell fragments cemented together"], "correct_index": 1, "difficulty": 1, "explanation": "Igneous rocks form from cooled magma (underground) or lava (surface). Granite and basalt are igneous. Sedimentary rocks form from compressed sediment. Metamorphic rocks form from existing rocks under heat/pressure.", "test_types": ["ASVAB"]},
    {"id": "GS060", "section": "General Science", "topic": "Rock Cycle", "question_text": "Fossils are most commonly found in which type of rock?", "options": ["Igneous", "Metamorphic", "Sedimentary", "Volcanic"], "correct_index": 2, "difficulty": 1, "explanation": "Fossils form when organisms are buried in sediment that gradually compresses into sedimentary rock. The high heat and pressure involved in forming igneous and metamorphic rocks destroys most fossils.", "test_types": ["ASVAB"]},
    {"id": "GS061", "section": "General Science", "topic": "Rock Cycle", "question_text": "Metamorphic rocks are formed when existing rocks are subjected to:", "options": ["Erosion by wind and water", "Extreme heat and pressure", "Cooling of molten material", "Chemical reactions with acids"], "correct_index": 1, "difficulty": 2, "explanation": "Metamorphic rocks (marble, slate, schist) form when existing rocks are changed by extreme heat and/or pressure without melting. If the rock melted, it would become magma and form igneous rock instead.", "test_types": ["ASVAB"]},

    # === EARTH SCIENCE: Weather ===
    {"id": "GS062", "section": "General Science", "topic": "Weather", "question_text": "A cold front typically brings:", "options": ["Gradual warming and light rain", "Clear skies and high pressure", "Sudden storms and temperature drop", "Fog and drizzle"], "correct_index": 2, "difficulty": 2, "explanation": "Cold fronts bring sudden, severe weather — thunderstorms, heavy rain, and a rapid temperature drop as cold air pushes under warm air. Warm fronts bring gradual warming and steady rain.", "test_types": ["ASVAB"]},
    {"id": "GS063", "section": "General Science", "topic": "Weather", "question_text": "Low atmospheric pressure is generally associated with:", "options": ["Clear, calm weather", "Storm development", "Cold, dry air", "High winds only"], "correct_index": 1, "difficulty": 2, "explanation": "Low pressure areas have rising air, which leads to cloud formation and storms. High pressure areas have sinking air, associated with clear, calm weather. Meteorologists watch pressure to forecast storms.", "test_types": ["ASVAB"]},

    # === EARTH SCIENCE: Water Cycle ===
    {"id": "GS064", "section": "General Science", "topic": "Water Cycle", "question_text": "Water vapor turning into liquid water droplets when cooled is called:", "options": ["Evaporation", "Precipitation", "Condensation", "Transpiration"], "correct_index": 2, "difficulty": 1, "explanation": "Condensation is the process by which water vapor cools and changes to liquid water — it forms clouds and dew. Evaporation is the reverse (liquid to gas). Precipitation is water falling from clouds.", "test_types": ["ASVAB"]},
    {"id": "GS065", "section": "General Science", "topic": "Water Cycle", "question_text": "In the water cycle, the energy source that drives evaporation is:", "options": ["Wind", "Gravity", "Sunlight", "The moon's gravity"], "correct_index": 2, "difficulty": 1, "explanation": "Sunlight provides the energy (heat) that evaporates water from oceans, lakes, and other surfaces. Gravity drives precipitation (water falling) and surface runoff. Wind helps distribute moisture.", "test_types": ["ASVAB"]},

    # === EARTH SCIENCE: Solar System ===
    {"id": "GS066", "section": "General Science", "topic": "Solar System", "question_text": "Which is the correct order of the inner planets from the Sun?", "options": ["Mercury, Earth, Venus, Mars", "Mercury, Venus, Earth, Mars", "Venus, Mercury, Earth, Mars", "Mars, Earth, Venus, Mercury"], "correct_index": 1, "difficulty": 1, "explanation": "The correct order is Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune. A common mnemonic: 'My Very Educated Mother Just Served Us Nachos'.", "test_types": ["ASVAB"]},
    {"id": "GS067", "section": "General Science", "topic": "Solar System", "question_text": "Which planet is the largest in our solar system?", "options": ["Saturn", "Neptune", "Earth", "Jupiter"], "correct_index": 3, "difficulty": 1, "explanation": "Jupiter is the largest planet, with a mass more than twice that of all other planets combined. It is a gas giant and has a famous storm called the Great Red Spot.", "test_types": ["ASVAB"]},
    {"id": "GS068", "section": "General Science", "topic": "Solar System", "question_text": "How many planets are in our solar system?", "options": ["7", "8", "9", "10"], "correct_index": 1, "difficulty": 1, "explanation": "There are 8 planets: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune. Pluto was reclassified as a dwarf planet in 2006.", "test_types": ["ASVAB"]},

    # === EARTH SCIENCE: Moon Phases ===
    {"id": "GS069", "section": "General Science", "topic": "Moon Phases", "question_text": "A full moon occurs when:", "options": ["The Moon is between the Earth and Sun", "The Earth is between the Moon and Sun", "The Sun is between the Earth and Moon", "The Moon is at its farthest point from Earth"], "correct_index": 1, "difficulty": 2, "explanation": "A full moon occurs when Earth is between the Sun and Moon, allowing the Moon's entire illuminated side to face Earth. A new moon occurs when the Moon is between Earth and the Sun.", "test_types": ["ASVAB"]},
    {"id": "GS070", "section": "General Science", "topic": "Moon Phases", "question_text": "A lunar eclipse occurs when:", "options": ["The Moon passes between Earth and the Sun", "Earth passes between the Sun and Moon, casting a shadow on the Moon", "The Moon is at its closest point to Earth", "The Sun's light reflects off Earth onto the Moon"], "correct_index": 1, "difficulty": 2, "explanation": "A lunar eclipse occurs when Earth passes directly between the Sun and Moon, casting Earth's shadow onto the Moon. A solar eclipse occurs when the Moon passes between Earth and the Sun.", "test_types": ["ASVAB"]},

    # === Additional chemistry/physics to round out 100 ===
    {"id": "GS071", "section": "General Science", "topic": "Chemistry", "question_text": "Which of the following is NOT a chemical change?", "options": ["Burning wood", "Rusting iron", "Dissolving sugar in water", "Baking bread"], "correct_index": 2, "difficulty": 2, "explanation": "Dissolving sugar in water is a physical change — the sugar can be recovered by evaporating the water and its chemical identity doesn't change. Burning, rusting, and baking all produce new chemical substances.", "test_types": ["ASVAB"]},
    {"id": "GS072", "section": "General Science", "topic": "Chemistry", "question_text": "The smallest unit of an element that retains the chemical properties of that element is:", "options": ["Molecule", "Compound", "Atom", "Ion"], "correct_index": 2, "difficulty": 1, "explanation": "An atom is the smallest unit of an element that still has that element's chemical properties. A molecule is two or more atoms bonded together. An ion is a charged atom.", "test_types": ["ASVAB"]},
    {"id": "GS073", "section": "General Science", "topic": "Physics", "question_text": "Potential energy stored due to an object's height above the ground is called:", "options": ["Kinetic energy", "Chemical energy", "Gravitational potential energy", "Thermal energy"], "correct_index": 2, "difficulty": 1, "explanation": "Gravitational potential energy is stored energy due to height (PE = mgh). As an object falls, PE converts to kinetic energy (energy of motion). Chemical energy is stored in bonds.", "test_types": ["ASVAB"]},
    {"id": "GS074", "section": "General Science", "topic": "Physics", "question_text": "According to the law of conservation of energy:", "options": ["Energy can be created from nothing in a nuclear reaction", "Energy can be destroyed by friction", "Energy cannot be created or destroyed, only converted", "Chemical reactions always create new energy"], "correct_index": 2, "difficulty": 2, "explanation": "The law of conservation of energy states that energy cannot be created or destroyed, only converted from one form to another. A light bulb converts electrical energy to light and heat.", "test_types": ["ASVAB"]},
    {"id": "GS075", "section": "General Science", "topic": "Life Science", "question_text": "Which blood type is the universal donor?", "options": ["Type A", "Type B", "Type AB", "Type O negative"], "correct_index": 3, "difficulty": 2, "explanation": "Type O negative blood lacks A, B, and Rh antigens, so it can be given to anyone without triggering an immune reaction. Type AB positive is the universal recipient (can receive any type).", "test_types": ["ASVAB"]},
    {"id": "GS076", "section": "General Science", "topic": "Life Science", "question_text": "Which organ is responsible for filtering blood and producing urine?", "options": ["Liver", "Pancreas", "Kidney", "Spleen"], "correct_index": 2, "difficulty": 1, "explanation": "The kidneys filter blood, removing waste products and excess water to produce urine. The liver detoxifies blood and produces bile. The pancreas produces insulin and digestive enzymes.", "test_types": ["ASVAB"]},
    {"id": "GS077", "section": "General Science", "topic": "Life Science", "question_text": "The function of red blood cells is to:", "options": ["Fight infection", "Carry oxygen via hemoglobin", "Clot wounds", "Produce antibodies"], "correct_index": 1, "difficulty": 1, "explanation": "Red blood cells (erythrocytes) carry oxygen using hemoglobin protein. White blood cells fight infection. Platelets clot wounds. Antibodies are produced by B lymphocytes (a type of white blood cell).", "test_types": ["ASVAB"]},
    {"id": "GS078", "section": "General Science", "topic": "Life Science", "question_text": "Photosynthesis produces oxygen as a byproduct. Where does this oxygen come from?", "options": ["Carbon dioxide molecules", "Water molecules split by light energy", "Glucose breakdown", "Atmospheric nitrogen"], "correct_index": 1, "difficulty": 3, "explanation": "During the light reactions of photosynthesis, water molecules (H2O) are split by light energy. The oxygen atoms from water are released as O2 gas — this is the origin of the oxygen we breathe.", "test_types": ["ASVAB"]},
    {"id": "GS079", "section": "General Science", "topic": "Earth Science", "question_text": "What force causes tides on Earth?", "options": ["Earth's rotation", "Atmospheric pressure", "The Moon's gravitational pull", "Ocean currents"], "correct_index": 2, "difficulty": 1, "explanation": "Tides are caused primarily by the Moon's gravitational pull on Earth's oceans. The Sun also influences tides but to a lesser extent. Earth's rotation affects the timing of tides.", "test_types": ["ASVAB"]},
    {"id": "GS080", "section": "General Science", "topic": "Earth Science", "question_text": "Which of the following correctly describes a food chain?", "options": ["Hawk → Snake → Mouse → Grass", "Grass → Mouse → Snake → Hawk", "Snake → Hawk → Grass → Mouse", "Mouse → Grass → Hawk → Snake"], "correct_index": 1, "difficulty": 1, "explanation": "Food chains go from producer to consumer: Grass (producer) → Mouse (primary consumer) → Snake (secondary consumer) → Hawk (tertiary consumer). Energy flows from left to right.", "test_types": ["ASVAB"]},
    {"id": "GS081", "section": "General Science", "topic": "Chemistry", "question_text": "What is the chemical formula for water?", "options": ["HO", "H2O2", "H2O", "OH2"], "correct_index": 2, "difficulty": 1, "explanation": "Water is H2O — two hydrogen atoms bonded to one oxygen atom. H2O2 is hydrogen peroxide. Water's bent molecular shape gives it polarity, which is responsible for many of its unique properties.", "test_types": ["ASVAB"]},
    {"id": "GS082", "section": "General Science", "topic": "Physics", "question_text": "An object moving in a circular path requires a force directed toward the center of the circle. This force is called:", "options": ["Centrifugal force", "Centripetal force", "Gravitational force", "Normal force"], "correct_index": 1, "difficulty": 2, "explanation": "Centripetal force (meaning 'center-seeking') is directed toward the center of circular motion. Gravity provides the centripetal force for orbiting objects. Centrifugal force is a fictitious outward force.", "test_types": ["ASVAB"]},
    {"id": "GS083", "section": "General Science", "topic": "Life Science", "question_text": "The nervous system transmits signals to and from the brain using:", "options": ["Blood vessels", "Neurons", "Hormones", "Lymph nodes"], "correct_index": 1, "difficulty": 1, "explanation": "Neurons are the specialized cells of the nervous system that transmit electrical signals. The brain and spinal cord form the central nervous system. Hormones are chemical messengers used by the endocrine system.", "test_types": ["ASVAB"]},
    {"id": "GS084", "section": "General Science", "topic": "Life Science", "question_text": "Which of the following is an example of a mutualistic relationship?", "options": ["A lion eating a zebra", "A tapeworm living in a host", "Bees pollinating flowers while collecting nectar", "A cuckoo bird laying eggs in another bird's nest"], "correct_index": 2, "difficulty": 2, "explanation": "Mutualism is when both species benefit. Bees get nectar (food) and flowers get pollinated (reproduction). Predation (lion/zebra) and parasitism (tapeworm, cuckoo) benefit only one organism.", "test_types": ["ASVAB"]},
    {"id": "GS085", "section": "General Science", "topic": "Chemistry", "question_text": "During electrolysis, water splits into:", "options": ["Carbon dioxide and hydrogen", "Hydrogen and oxygen", "Sodium and chlorine", "Oxygen and carbon"], "correct_index": 1, "difficulty": 2, "explanation": "Electrolysis of water (H2O) splits it into hydrogen gas (H2) at the negative electrode and oxygen gas (O2) at the positive electrode. The ratio is 2:1 hydrogen to oxygen by volume.", "test_types": ["ASVAB"]},
    {"id": "GS086", "section": "General Science", "topic": "Physics", "question_text": "Which type of simple machine multiplies force by using a wheel rotating on an axle?", "options": ["Pulley", "Lever", "Wheel and axle", "Wedge"], "correct_index": 2, "difficulty": 2, "explanation": "A wheel and axle multiplies force — turning a large wheel produces greater force at the smaller axle (or vice versa). A steering wheel and screwdriver handle are examples. Pulleys redirect force using rope and wheel.", "test_types": ["ASVAB"]},
    {"id": "GS087", "section": "General Science", "topic": "Life Science", "question_text": "Which macronutrient provides the most energy per gram?", "options": ["Carbohydrates (4 cal/g)", "Protein (4 cal/g)", "Fat (9 cal/g)", "Fiber (2 cal/g)"], "correct_index": 2, "difficulty": 2, "explanation": "Fat provides 9 calories per gram — more than twice the energy of carbohydrates or protein (both 4 cal/g). This is why fat is an efficient long-term energy storage form in the body.", "test_types": ["ASVAB"]},
    {"id": "GS088", "section": "General Science", "topic": "Earth Science", "question_text": "The process by which plants release water vapor through their leaves is called:", "options": ["Evaporation", "Transpiration", "Condensation", "Respiration"], "correct_index": 1, "difficulty": 2, "explanation": "Transpiration is the release of water vapor from plant leaves through tiny pores called stomata. It is distinct from evaporation (water leaving a surface) and is an important part of the water cycle.", "test_types": ["ASVAB"]},
    {"id": "GS089", "section": "General Science", "topic": "Chemistry", "question_text": "On the periodic table, elements in the same period (row) have:", "options": ["The same number of valence electrons", "The same number of electron shells (energy levels)", "Similar chemical properties", "The same atomic mass"], "correct_index": 1, "difficulty": 3, "explanation": "Elements in the same period have the same number of electron shells. For example, all period 3 elements have 3 electron shells. Elements in the same group (column) have similar properties due to the same number of valence electrons.", "test_types": ["ASVAB"]},
    {"id": "GS090", "section": "General Science", "topic": "Life Science", "question_text": "What is the role of insulin in the body?", "options": ["Increase blood sugar levels", "Lower blood sugar by allowing cells to absorb glucose", "Digest fats", "Regulate blood pressure"], "correct_index": 1, "difficulty": 2, "explanation": "Insulin, produced by the pancreas, signals cells to absorb glucose from the blood, lowering blood sugar levels. Glucagon does the opposite. Diabetes involves problems with insulin production or response.", "test_types": ["ASVAB"]},
    {"id": "GS091", "section": "General Science", "topic": "Physics", "question_text": "Which of Newton's laws explains why a rocket accelerates when gases are expelled?", "options": ["First law (inertia)", "Second law (F=ma)", "Third law (action-reaction)", "Law of gravity"], "correct_index": 2, "difficulty": 2, "explanation": "Newton's third law: the rocket expels gas downward (action), and the gas pushes the rocket upward with equal force (reaction). F=ma explains the relationship between force, mass, and acceleration.", "test_types": ["ASVAB"]},
    {"id": "GS092", "section": "General Science", "topic": "Earth Science", "question_text": "What causes the seasons on Earth?", "options": ["Earth's distance from the Sun changing", "Earth's tilted axis as it orbits the Sun", "The Sun's changing energy output", "The Moon's gravitational pull"], "correct_index": 1, "difficulty": 2, "explanation": "Seasons are caused by Earth's 23.5-degree axial tilt as it orbits the Sun. When a hemisphere tilts toward the Sun it receives more direct sunlight (summer). Earth's distance from the Sun changes very little.", "test_types": ["ASVAB"]},
    {"id": "GS093", "section": "General Science", "topic": "Life Science", "question_text": "Viruses are different from bacteria because viruses:", "options": ["Are larger than bacteria", "Can reproduce on their own", "Are not made of cells and require a host to reproduce", "Can be killed by antibiotics"], "correct_index": 2, "difficulty": 2, "explanation": "Viruses are not cells — they are particles of genetic material (DNA or RNA) in a protein coat. They cannot reproduce without hijacking a host cell. Antibiotics work on bacteria, not viruses.", "test_types": ["ASVAB"]},
    {"id": "GS094", "section": "General Science", "topic": "Chemistry", "question_text": "A substance that speeds up a chemical reaction without being consumed is called a:", "options": ["Reactant", "Product", "Catalyst", "Solvent"], "correct_index": 2, "difficulty": 2, "explanation": "A catalyst speeds up a reaction by lowering the activation energy, but is not used up in the process. Enzymes are biological catalysts. Reactants are consumed in reactions. Products are formed.", "test_types": ["ASVAB"]},
    {"id": "GS095", "section": "General Science", "topic": "Physics", "question_text": "Density is defined as:", "options": ["Mass times volume", "Mass divided by volume", "Volume divided by mass", "Weight divided by area"], "correct_index": 1, "difficulty": 1, "explanation": "Density = mass ÷ volume (D = m/V). A dense material has a lot of mass packed into a small volume. Water's density is 1 g/cm³ — objects less dense than water float, objects more dense sink.", "test_types": ["ASVAB"]},
    {"id": "GS096", "section": "General Science", "topic": "Earth Science", "question_text": "What percentage of Earth's surface is covered by water?", "options": ["50%", "60%", "71%", "85%"], "correct_index": 2, "difficulty": 1, "explanation": "Approximately 71% of Earth's surface is covered by water, mostly the oceans. About 97% of that water is salt water in the oceans, leaving only 3% as fresh water.", "test_types": ["ASVAB"]},
    {"id": "GS097", "section": "General Science", "topic": "Life Science", "question_text": "The process by which plants make food is called photosynthesis. Plants need all of the following EXCEPT:", "options": ["Carbon dioxide", "Sunlight", "Oxygen", "Water"], "correct_index": 2, "difficulty": 2, "explanation": "Photosynthesis requires CO2, sunlight, and water. Oxygen is a PRODUCT of photosynthesis, not a reactant. The equation: 6CO2 + 6H2O + light → C6H12O6 + 6O2.", "test_types": ["ASVAB"]},
    {"id": "GS098", "section": "General Science", "topic": "Chemistry", "question_text": "When iron combines with oxygen and water to form rust, this is an example of:", "options": ["A physical change", "Sublimation", "Oxidation", "Condensation"], "correct_index": 2, "difficulty": 2, "explanation": "Rusting is oxidation — iron reacts with oxygen and water to form iron oxide (Fe2O3). It is a chemical change because a new substance (rust) is formed with different properties than the original iron.", "test_types": ["ASVAB"]},
    {"id": "GS099", "section": "General Science", "topic": "Physics", "question_text": "An object at the top of a hill has maximum:", "options": ["Kinetic energy", "Thermal energy", "Potential energy", "Mechanical energy"], "correct_index": 2, "difficulty": 1, "explanation": "At the top of a hill, an object has maximum gravitational potential energy (stored due to height). As it rolls down, PE converts to kinetic energy (energy of motion). At the bottom, KE is maximum.", "test_types": ["ASVAB"]},
    {"id": "GS100", "section": "General Science", "topic": "Life Science", "question_text": "The heart pumps blood through how many separate circuits in the body?", "options": ["One", "Two", "Three", "Four"], "correct_index": 1, "difficulty": 2, "explanation": "The heart has two circuits: pulmonary circulation (heart to lungs and back, to pick up oxygen) and systemic circulation (heart to the body and back, to deliver oxygen). The heart's four chambers support these two loops.", "test_types": ["ASVAB"]},
]

if __name__ == "__main__":
    print(f"GS question count: {len(GS_QUESTIONS)}")
